UPDATE HOSPITAL_OWNER_REQUEST
SET DOCUMENT_URL = '/pdf/owner-request-'
    || LPAD(REQUEST_ID, 3, '0')
    || '.pdf'
WHERE REQUEST_ID BETWEEN 1 AND 100;

-- 폴더는 스태틱 -> pdf -> 여기에 넣으시고 requestId에 맞춰서 pdf도 설정하세요

COMMIT;

SELECT REQUEST_ID, DOCUMENT_URL
FROM HOSPITAL_OWNER_REQUEST
WHERE REQUEST_ID BETWEEN 1 AND 10
ORDER BY REQUEST_ID;