/* ============================================================================
   PetCity 01 - 회원 및 회원 보안 이력

   선행 파일: 없음
   포함 내용: 테이블, PK/UNIQUE/CHECK, 외래키, 관련 인덱스, 관련 시퀀스
   제외 내용: 테스트·샘플 회원/병원/게시글/리뷰/신청 더미 데이터
============================================================================ */


/* 1. 시퀀스 */

CREATE SEQUENCE SEQ_APP_MEMBER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_MEMBER_SECURITY_AUDIT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


/* 2. 테이블 */

CREATE TABLE APP_MEMBER (
    MEMBER_ID NUMBER,
    NICKNAME VARCHAR2(50 CHAR) NOT NULL,
    EMAIL VARCHAR2(100 CHAR),
    PHONE VARCHAR2(30 CHAR),
    ROLE VARCHAR2(20 CHAR) DEFAULT 'USER' NOT NULL,
    CREATED_AT TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP (6),
    PROFILE_IMAGE VARCHAR2(1000 CHAR),
    LOGIN_ID VARCHAR2(150 CHAR) NOT NULL,
    PASSWORD VARCHAR2(200 CHAR) NOT NULL,
    EMAIL_VERIFIED CHAR(1) DEFAULT 'N' NOT NULL,
    STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    LAST_LOGIN_AT TIMESTAMP (6),
    MEMBER_STATUS VARCHAR2(30 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    DELETE_REQUESTED_AT TIMESTAMP (6),
    HARD_DELETE_AT TIMESTAMP (6),
    DELETED_AT TIMESTAMP (6),
    DELETE_REASON VARCHAR2(500),
    BLOCKED_AT TIMESTAMP (6),
    BLOCKED_BY NUMBER,
    LOGIN_TYPE VARCHAR2(20),
    SOCIAL_ID VARCHAR2(100),
    AGREEMENT_EMAIL CHAR(1) DEFAULT 'N',
    RECOVERY_TOKEN_HASH VARCHAR2(200 CHAR),
    CONSTRAINT CK_APP_MEMBER_ROLE CHECK (ROLE IN ('USER', 'OWNER', 'ADMIN')),
    CONSTRAINT CK_APP_MEMBER_EMAIL_VERIFIED CHECK (EMAIL_VERIFIED IN ('Y', 'N')),
    CONSTRAINT CK_APP_MEMBER_STATUS CHECK (STATUS IN ('ACTIVE', 'BLOCKED', 'DELETED')),
    CONSTRAINT CK_APP_MEMBER_MEMBER_STATUS CHECK (MEMBER_STATUS IN ('ACTIVE', 'DELETE_PENDING', 'DELETED')),
    CONSTRAINT PK_APP_MEMBER PRIMARY KEY (MEMBER_ID),
    CONSTRAINT UQ_APP_MEMBER_LOGIN_ID UNIQUE (LOGIN_ID)
);

CREATE TABLE MEMBER_SECURITY_AUDIT (
    AUDIT_ID NUMBER,
    MEMBER_ID NUMBER,
    LOGIN_ID VARCHAR2(100 CHAR) NOT NULL,
    NICKNAME VARCHAR2(100 CHAR),
    LOGIN_TYPE VARCHAR2(30 CHAR),
    EVENT_TYPE VARCHAR2(50 CHAR) NOT NULL,
    EVENT_RESULT VARCHAR2(20 CHAR) NOT NULL,
    EVENT_REASON VARCHAR2(1000 CHAR),
    IP_ADDRESS VARCHAR2(64 CHAR),
    OCCURRED_AT TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL,
    EXPIRES_AT TIMESTAMP (6) NOT NULL,
    CONSTRAINT CK_MEMBER_SECURITY_AUDIT_RESULT CHECK (EVENT_RESULT IN ('SUCCESS', 'FAILURE')),
    CONSTRAINT PK_MEMBER_SECURITY_AUDIT PRIMARY KEY (AUDIT_ID)
);


/* 4. 조회·업무 인덱스 */

CREATE INDEX IX_MEMBER_SECURITY_AUDIT_MEMBER
    ON MEMBER_SECURITY_AUDIT (MEMBER_ID, OCCURRED_AT DESC);

CREATE INDEX IX_MEMBER_SECURITY_AUDIT_EXPIRES
    ON MEMBER_SECURITY_AUDIT (EXPIRES_AT);


COMMIT;



/* ============================================================================
   시연용 회원 데이터

   - 관리자: admin / 비밀번호 1234
   - 일반회원: test001 ~ test200 / 비밀번호 1234
   - 기존 LOGIN_ID가 있으면 해당 계정은 건너뜁니다.
============================================================================ */

INSERT INTO APP_MEMBER (
    MEMBER_ID,
    LOGIN_ID,
    PASSWORD,
    NICKNAME,
    ROLE,
    EMAIL_VERIFIED,
    STATUS,
    MEMBER_STATUS,
    CREATED_AT,
    UPDATED_AT
)
SELECT
    SEQ_APP_MEMBER.NEXTVAL,
    'admin',
    '$2a$10$CIU/6.QNVORtdY41VTyVje2cmIKfzPYud.sZ8GGmCO8dtqWid0CEi',
    '관리자',
    'ADMIN',
    'Y',
    'ACTIVE',
    'ACTIVE',
    LOCALTIMESTAMP,
    LOCALTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1
    FROM APP_MEMBER
    WHERE LOGIN_ID = 'admin'
);

COMMIT;


DECLARE
    V_PASSWORD CONSTANT VARCHAR2(200) :=
        '$2a$10$CIU/6.QNVORtdY41VTyVje2cmIKfzPYud.sZ8GGmCO8dtqWid0CEi';

    V_STATUS              APP_MEMBER.STATUS%TYPE;
    V_MEMBER_STATUS       APP_MEMBER.MEMBER_STATUS%TYPE;
    V_LAST_LOGIN_AT       APP_MEMBER.LAST_LOGIN_AT%TYPE;
    V_BLOCKED_AT          APP_MEMBER.BLOCKED_AT%TYPE;
    V_DELETE_REQUESTED_AT APP_MEMBER.DELETE_REQUESTED_AT%TYPE;
    V_DELETED_AT          APP_MEMBER.DELETED_AT%TYPE;
    V_HARD_DELETE_AT      APP_MEMBER.HARD_DELETE_AT%TYPE;
    V_DELETE_REASON       APP_MEMBER.DELETE_REASON%TYPE;
BEGIN
    FOR I IN 1..200 LOOP
        V_BLOCKED_AT := NULL;
        V_DELETE_REQUESTED_AT := NULL;
        V_DELETED_AT := NULL;
        V_HARD_DELETE_AT := NULL;
        V_DELETE_REASON := NULL;

        IF I <= 180 THEN
            V_STATUS := 'ACTIVE';
            V_MEMBER_STATUS := 'ACTIVE';
            V_LAST_LOGIN_AT :=
                LOCALTIMESTAMP
                - NUMTODSINTERVAL(MOD(I, 90), 'DAY');
        ELSE
            V_STATUS := 'DELETED';
            V_MEMBER_STATUS := 'DELETED';
            V_LAST_LOGIN_AT := ADD_MONTHS(LOCALTIMESTAMP, -13);
            V_DELETE_REQUESTED_AT := LOCALTIMESTAMP - INTERVAL '1' DAY;
            V_DELETED_AT := LOCALTIMESTAMP - INTERVAL '1' DAY;
            V_HARD_DELETE_AT := LOCALTIMESTAMP + INTERVAL '30' DAY;
            V_DELETE_REASON := '테스트용 삭제 상태 회원';
        END IF;

        INSERT INTO APP_MEMBER (
            MEMBER_ID,
            LOGIN_ID,
            PASSWORD,
            NICKNAME,
            EMAIL,
            PHONE,
            ROLE,
            CREATED_AT,
            UPDATED_AT,
            PROFILE_IMAGE,
            EMAIL_VERIFIED,
            STATUS,
            LAST_LOGIN_AT,
            MEMBER_STATUS,
            DELETE_REQUESTED_AT,
            HARD_DELETE_AT,
            DELETED_AT,
            BLOCKED_AT,
            DELETE_REASON
        )
        SELECT
            SEQ_APP_MEMBER.NEXTVAL,
            'test' || LPAD(I, 3, '0'),
            V_PASSWORD,
            '테스트회원' || LPAD(I, 3, '0'),
            'test' || LPAD(I, 3, '0') || '@petcity.test',
            '010-9000-' || LPAD(I, 4, '0'),
            'USER',
            LOCALTIMESTAMP - NUMTODSINTERVAL(MOD(I, 180), 'DAY'),
            LOCALTIMESTAMP,
            NULL,
            'Y',
            V_STATUS,
            V_LAST_LOGIN_AT,
            V_MEMBER_STATUS,
            V_DELETE_REQUESTED_AT,
            V_HARD_DELETE_AT,
            V_DELETED_AT,
            V_BLOCKED_AT,
            V_DELETE_REASON
        FROM DUAL
        WHERE NOT EXISTS (
            SELECT 1
            FROM APP_MEMBER
            WHERE LOGIN_ID = 'test' || LPAD(I, 3, '0')
        );
    END LOOP;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

SELECT ROLE, STATUS, MEMBER_STATUS, COUNT(*) AS MEMBER_COUNT
FROM APP_MEMBER
GROUP BY ROLE, STATUS, MEMBER_STATUS
ORDER BY ROLE, STATUS, MEMBER_STATUS;
