/* ============================================================================
   PetCity 02 - 동물 종류·진료 서비스·진료과목 기준 테이블

   선행 파일: 없음 (01과 순서를 바꾸어도 되지만 번호 순서 권장)
   포함 내용: 테이블, PK/UNIQUE/CHECK, 외래키, 관련 인덱스, 관련 시퀀스
   제외 내용: 테스트·샘플 회원/병원/게시글/리뷰/신청 더미 데이터
============================================================================ */

-- 서비스 구동에 필요한 기준 데이터만 포함하며 테스트 더미 데이터는 포함하지 않습니다.


/* 1. 시퀀스 */

CREATE SEQUENCE SEQ_ANIMAL_TYPE START WITH 38 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_MEDICAL_SERVICE START WITH 10 INCREMENT BY 1 NOCACHE NOCYCLE;


/* 2. 테이블 */

CREATE TABLE ANIMAL_TYPE (
    ANIMAL_ID NUMBER,
    ANIMAL_NAME VARCHAR2(50 CHAR) NOT NULL,
    CATEGORY VARCHAR2(50 CHAR) NOT NULL,
    PARENT_ID NUMBER,
    CONSTRAINT PK_ANIMAL_TYPE PRIMARY KEY (ANIMAL_ID)
);

CREATE TABLE MEDICAL_SERVICE (
    SERVICE_ID NUMBER,
    SERVICE_NAME VARCHAR2(50 CHAR) NOT NULL,
    CONSTRAINT PK_MEDICAL_SERVICE PRIMARY KEY (SERVICE_ID)
);

CREATE TABLE MEDICAL_SUBJECT (
    SUBJECT_ID NUMBER,
    SUBJECT_NAME VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_MEDICAL_SUBJECT PRIMARY KEY (SUBJECT_ID)
);


/* 3. 외래키 */

ALTER TABLE ANIMAL_TYPE
    ADD CONSTRAINT FK_ANIMAL_PARENT
    FOREIGN KEY (PARENT_ID)
    REFERENCES ANIMAL_TYPE (ANIMAL_ID);


/* 6. 필수 기준 데이터 */

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (1, '강아지', '일반', NULL);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (2, '고양이', '일반', NULL);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (3, '파충류', '특수', NULL);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (4, '설치류', '특수', NULL);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (5, '어류', '특수', NULL);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (6, '말티즈', '일반', 1);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (7, '시츄', '일반', 1);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (8, '골든리트리버', '일반', 1);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (9, '보더콜리', '일반', 1);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (10, '비숑프리제', '일반', 1);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (11, '기타(소형견)', '일반', 1);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (12, '기타(중형견)', '일반', 1);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (13, '기타(대형견)', '일반', 1);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (14, '코리안숏헤어', '일반', 2);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (15, '아메리칸숏헤어', '일반', 2);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (16, '먼치킨', '일반', 2);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (17, '페르시안', '일반', 2);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (18, '러시안블루', '일반', 2);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (19, '샤미즈', '일반', 2);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (20, '스코티시폴드', '일반', 2);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (21, '기타묘', '일반', 2);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (22, '도마뱀', '특수', 3);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (23, '거북이', '특수', 3);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (24, '뱀', '특수', 3);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (25, '카멜레온', '특수', 3);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (26, '기타', '특수', 3);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (27, '다람쥐', '특수', 4);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (28, '날다람쥐', '특수', 4);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (29, '햄스터', '특수', 4);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (30, '토끼', '특수', 4);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (31, '친칠라', '특수', 4);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (32, '기타', '특수', 4);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (33, '금붕어', '특수', 5);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (34, '잉어', '특수', 5);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (35, '열대어', '특수', 5);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (36, '고대어', '특수', 5);

INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (37, '기타', '특수', 5);

INSERT INTO MEDICAL_SERVICE (SERVICE_ID, SERVICE_NAME) VALUES (1, '일반진료');

INSERT INTO MEDICAL_SERVICE (SERVICE_ID, SERVICE_NAME) VALUES (2, '응급진료');

INSERT INTO MEDICAL_SERVICE (SERVICE_ID, SERVICE_NAME) VALUES (3, '특수동물진료');

INSERT INTO MEDICAL_SERVICE (SERVICE_ID, SERVICE_NAME) VALUES (4, '건강검진');

INSERT INTO MEDICAL_SERVICE (SERVICE_ID, SERVICE_NAME) VALUES (5, '예방접종');

INSERT INTO MEDICAL_SERVICE (SERVICE_ID, SERVICE_NAME) VALUES (6, '수술 가능');

INSERT INTO MEDICAL_SERVICE (SERVICE_ID, SERVICE_NAME) VALUES (7, '입원 가능');

INSERT INTO MEDICAL_SERVICE (SERVICE_ID, SERVICE_NAME) VALUES (8, '수술실 보유');

INSERT INTO MEDICAL_SERVICE (SERVICE_ID, SERVICE_NAME) VALUES (9, '입원실 보유');

INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (1, '내과');

INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (2, '외과');

INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (3, '정형외과');

INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (4, '피부과');

INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (5, '안과');

INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (6, '치과');

INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (7, '영상의학과');

INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (8, '이비인후과');

INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (9, '비뇨기과');

INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (10, '신경외과');

INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (11, '산과');

INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (12, '심장내과');

INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (13, '마취통증의학과');

INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (14, '예방의학과');

INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (15, '재활의학과');

INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (16, '중성화');

INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (17, '영양상담');

INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (18, '헌혈');

INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (19, '미용');


COMMIT;
