/* ============================================================================
   PetCity 03 - 회원 반려동물

   선행 파일: 01_member.sql, 02_animal_medical_master.sql
   포함 내용: 테이블, PK/UNIQUE/CHECK, 외래키, 관련 인덱스, 관련 시퀀스
   제외 내용: 테스트·샘플 회원/병원/게시글/리뷰/신청 더미 데이터
============================================================================ */


/* 1. 시퀀스 */

CREATE SEQUENCE SEQ_MEMBER_PET START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


/* 2. 테이블 */

CREATE TABLE MEMBER_PET (
    PET_ID NUMBER,
    MEMBER_ID NUMBER NOT NULL,
    ANIMAL_ID NUMBER NOT NULL,
    PET_NAME VARCHAR2(50 CHAR) NOT NULL,
    BREED_NAME VARCHAR2(100 CHAR),
    GENDER CHAR(1) DEFAULT 'U' NOT NULL,
    BIRTH_DATE DATE,
    WEIGHT NUMBER(6,2),
    PHOTO_URL VARCHAR2(1000 CHAR),
    REGISTRATION_NO VARCHAR2(100 CHAR),
    NEUTERED CHAR(1) DEFAULT 'U' NOT NULL,
    ALLERGY_NOTE VARCHAR2(500 CHAR),
    NOTE VARCHAR2(1000 CHAR),
    IS_MAIN CHAR(1) DEFAULT 'N' NOT NULL,
    STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP (6),
    CONSTRAINT CK_MEMBER_PET_GENDER CHECK (GENDER IN ('M', 'F', 'U')),
    CONSTRAINT CK_MEMBER_PET_NEUTERED CHECK (NEUTERED IN ('Y', 'N', 'U')),
    CONSTRAINT CK_MEMBER_PET_IS_MAIN CHECK (IS_MAIN IN ('Y', 'N')),
    CONSTRAINT CK_MEMBER_PET_STATUS CHECK (STATUS IN ('ACTIVE', 'DELETED')),
    CONSTRAINT PK_MEMBER_PET PRIMARY KEY (PET_ID)
);


/* 3. 외래키 */

ALTER TABLE MEMBER_PET
    ADD CONSTRAINT FK_MEMBER_PET_MEMBER
    FOREIGN KEY (MEMBER_ID)
    REFERENCES APP_MEMBER (MEMBER_ID)
    ON DELETE CASCADE;

ALTER TABLE MEMBER_PET
    ADD CONSTRAINT FK_MEMBER_PET_ANIMAL
    FOREIGN KEY (ANIMAL_ID)
    REFERENCES ANIMAL_TYPE (ANIMAL_ID);


COMMIT;
