/* ============================================================================
   PetCity 04 - 병원 및 병원 진료 연결 테이블

   선행 파일: 01_member.sql, 02_animal_medical_master.sql
   포함 내용: 테이블, PK/UNIQUE/CHECK, 외래키, 관련 인덱스, 관련 시퀀스
   제외 내용: 테스트·샘플 회원/병원/게시글/리뷰/신청 더미 데이터
============================================================================ */


/* 1. 시퀀스 */

CREATE SEQUENCE SEQ_HOSPITAL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


/* 2. 테이블 */

CREATE TABLE HOSPITAL (
    HOSPITAL_ID NUMBER,
    OWNER_ID NUMBER,
    NAME VARCHAR2(200 CHAR) NOT NULL,
    ADDRESS VARCHAR2(500 CHAR) NOT NULL,
    DETAIL_ADDRESS VARCHAR2(500 CHAR),
    PHONE VARCHAR2(50 CHAR),
    LATITUDE NUMBER(18,9),
    LONGITUDE NUMBER(18,9),
    OPEN_TIME VARCHAR2(1000 CHAR),
    CLOSE_TIME VARCHAR2(1000 CHAR),
    STATUS VARCHAR2(30 CHAR) DEFAULT 'OPEN' NOT NULL,
    DESCRIPTION VARCHAR2(2000 CHAR),
    IMAGE_URL VARCHAR2(1000 CHAR),
    CREATED_AT TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP (6),
    WEBSITE_URL VARCHAR2(1000 CHAR),
    DISTRICT VARCHAR2(50 CHAR),
    STATUS_CODE VARCHAR2(20 CHAR),
    OPERATION_STATUS_TEXT VARCHAR2(100 CHAR),
    DATA_UPDATED_AT VARCHAR2(30 CHAR),
    LAST_MODIFIED_AT VARCHAR2(30 CHAR),
    BREAK_TIME VARCHAR2(1000 CHAR),
    CLOSED_DAYS VARCHAR2(500 CHAR),
    MEDICAL_SUBJECTS VARCHAR2(2000 CHAR),
    DOCTOR_INFO VARCHAR2(1000 CHAR),
    OWNER_NAME VARCHAR2(100 CHAR),
    SOURCE_URL VARCHAR2(1000 CHAR),
    CHECKED_AT VARCHAR2(30 CHAR),
    NOTE VARCHAR2(2000 CHAR),
    CONSTRAINT CK_HOSPITAL_STATUS CHECK (STATUS IN ('OPEN', 'CLOSED', 'TEMP_CLOSED')),
    CONSTRAINT PK_HOSPITAL PRIMARY KEY (HOSPITAL_ID)
);

CREATE TABLE HOSPITAL_ANIMAL (
    HOSPITAL_ID NUMBER NOT NULL,
    ANIMAL_ID NUMBER NOT NULL,
    CONSTRAINT PK_HOSPITAL_ANIMAL PRIMARY KEY (HOSPITAL_ID, ANIMAL_ID)
);

CREATE TABLE HOSPITAL_SERVICE (
    HOSPITAL_ID NUMBER NOT NULL,
    SERVICE_ID NUMBER NOT NULL,
    CONSTRAINT PK_HOSPITAL_SERVICE PRIMARY KEY (HOSPITAL_ID, SERVICE_ID)
);

CREATE TABLE HOSPITAL_MEDICAL_SUBJECT (
    HOSPITAL_ID NUMBER NOT NULL,
    SUBJECT_ID NUMBER NOT NULL,
    CONSTRAINT PK_HOSPITAL_MED_SUBJ PRIMARY KEY (HOSPITAL_ID, SUBJECT_ID)
);


/* 3. 외래키 */

ALTER TABLE HOSPITAL
    ADD CONSTRAINT FK_HOSPITAL_OWNER
    FOREIGN KEY (OWNER_ID)
    REFERENCES APP_MEMBER (MEMBER_ID)
    ON DELETE SET NULL;

ALTER TABLE HOSPITAL_ANIMAL
    ADD CONSTRAINT FK_HA_HOSPITAL
    FOREIGN KEY (HOSPITAL_ID)
    REFERENCES HOSPITAL (HOSPITAL_ID)
    ON DELETE CASCADE;

ALTER TABLE HOSPITAL_ANIMAL
    ADD CONSTRAINT FK_HA_ANIMAL
    FOREIGN KEY (ANIMAL_ID)
    REFERENCES ANIMAL_TYPE (ANIMAL_ID)
    ON DELETE CASCADE;

ALTER TABLE HOSPITAL_MEDICAL_SUBJECT
    ADD CONSTRAINT FK_HOSPITAL_MED_HOSPITAL
    FOREIGN KEY (HOSPITAL_ID)
    REFERENCES HOSPITAL (HOSPITAL_ID)
    ON DELETE CASCADE;

ALTER TABLE HOSPITAL_MEDICAL_SUBJECT
    ADD CONSTRAINT FK_HOSPITAL_MED_SUBJECT
    FOREIGN KEY (SUBJECT_ID)
    REFERENCES MEDICAL_SUBJECT (SUBJECT_ID);

ALTER TABLE HOSPITAL_SERVICE
    ADD CONSTRAINT FK_HS_HOSPITAL
    FOREIGN KEY (HOSPITAL_ID)
    REFERENCES HOSPITAL (HOSPITAL_ID)
    ON DELETE CASCADE;

ALTER TABLE HOSPITAL_SERVICE
    ADD CONSTRAINT FK_HS_SERVICE
    FOREIGN KEY (SERVICE_ID)
    REFERENCES MEDICAL_SERVICE (SERVICE_ID)
    ON DELETE CASCADE;


/* 4. 조회·업무 인덱스 */

CREATE INDEX IDX_HOSPITAL_MED_SUBJECT
    ON HOSPITAL_MEDICAL_SUBJECT (SUBJECT_ID);


COMMIT;
