/* ============================================================================
   PetCity 05 - 병원 리뷰·좋아요·즐겨찾기

   선행 파일: 01_member.sql, 03_member_pet.sql, 04_hospital_core.sql
   포함 내용: 테이블, PK/UNIQUE/CHECK, 외래키, 관련 인덱스, 관련 시퀀스
   제외 내용: 테스트·샘플 회원/병원/게시글/리뷰/신청 더미 데이터
============================================================================ */


/* 1. 시퀀스 */

CREATE SEQUENCE SEQ_HOSPITAL_REVIEW START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


/* 2. 테이블 */

CREATE TABLE HOSPITAL_REVIEW (
    REVIEW_ID NUMBER,
    HOSPITAL_ID NUMBER NOT NULL,
    MEMBER_ID NUMBER NOT NULL,
    RATING NUMBER(2,1) NOT NULL,
    CONTENT VARCHAR2(1000 CHAR),
    IMAGE_URL VARCHAR2(1000 CHAR),
    CREATED_AT TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP (6),
    PET_ID NUMBER,
    REPLY_CONTENT VARCHAR2(2000),
    REPLY_CREATED_AT TIMESTAMP (6),
    REPLY_ROLE VARCHAR2(20),
    CONSTRAINT CK_HOSPITAL_REVIEW_RATING CHECK (RATING BETWEEN 0 AND 5),
    CONSTRAINT PK_HOSPITAL_REVIEW PRIMARY KEY (REVIEW_ID)
);

CREATE TABLE HOSPITAL_LIKE (
    MEMBER_ID NUMBER NOT NULL,
    HOSPITAL_ID NUMBER NOT NULL,
    CREATED_AT TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_HOSPITAL_LIKE PRIMARY KEY (MEMBER_ID, HOSPITAL_ID)
);

CREATE TABLE FAVORITE_HOSPITAL (
    MEMBER_ID NUMBER NOT NULL,
    HOSPITAL_ID NUMBER NOT NULL,
    CREATED_AT TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_FAVORITE_HOSPITAL PRIMARY KEY (MEMBER_ID, HOSPITAL_ID)
);


/* 3. 외래키 */

ALTER TABLE HOSPITAL_LIKE
    ADD CONSTRAINT FK_HLIKE_MEMBER
    FOREIGN KEY (MEMBER_ID)
    REFERENCES APP_MEMBER (MEMBER_ID)
    ON DELETE CASCADE;

ALTER TABLE HOSPITAL_LIKE
    ADD CONSTRAINT FK_HLIKE_HOSPITAL
    FOREIGN KEY (HOSPITAL_ID)
    REFERENCES HOSPITAL (HOSPITAL_ID)
    ON DELETE CASCADE;

ALTER TABLE HOSPITAL_REVIEW
    ADD CONSTRAINT FK_REVIEW_HOSPITAL
    FOREIGN KEY (HOSPITAL_ID)
    REFERENCES HOSPITAL (HOSPITAL_ID)
    ON DELETE CASCADE;

ALTER TABLE HOSPITAL_REVIEW
    ADD CONSTRAINT FK_REVIEW_MEMBER
    FOREIGN KEY (MEMBER_ID)
    REFERENCES APP_MEMBER (MEMBER_ID)
    ON DELETE CASCADE;

ALTER TABLE FAVORITE_HOSPITAL
    ADD CONSTRAINT FK_FAV_MEMBER
    FOREIGN KEY (MEMBER_ID)
    REFERENCES APP_MEMBER (MEMBER_ID)
    ON DELETE CASCADE;

ALTER TABLE FAVORITE_HOSPITAL
    ADD CONSTRAINT FK_FAV_HOSPITAL
    FOREIGN KEY (HOSPITAL_ID)
    REFERENCES HOSPITAL (HOSPITAL_ID)
    ON DELETE CASCADE;


COMMIT;
