/* ============================================================================
   PetCity 07 - 게시판·댓글·이미지·조회 이력

   선행 파일: 01_member.sql, 02_animal_medical_master.sql
   포함 내용: 테이블, PK/UNIQUE/CHECK, 외래키, 관련 인덱스, 관련 시퀀스
   제외 내용: 테스트·샘플 회원/병원/게시글/리뷰/신청 더미 데이터
============================================================================ */


/* 1. 시퀀스 */

CREATE SEQUENCE SEQ_BOARD START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_BOARD_COMMENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_BOARD_IMAGE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


/* 2. 테이블 */

CREATE TABLE BOARD (
    BOARD_ID NUMBER,
    MEMBER_ID NUMBER NOT NULL,
    BOARD_TYPE VARCHAR2(30 CHAR) NOT NULL,
    TITLE VARCHAR2(200 CHAR) NOT NULL,
    HIT NUMBER DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP (6),
    ANIMAL_ID NUMBER,
    CONTENT CLOB,
    CONSTRAINT PK_BOARD PRIMARY KEY (BOARD_ID),
    CONSTRAINT CK_BOARD_TYPE CHECK (
                BOARD_TYPE IN (
                               'NOTICE',
                               'QNA',
                               'FREE',
                               'INFO',
                               'FAQ'
                    )
                )
);

CREATE TABLE BOARD_COMMENT (
    COMMENT_ID NUMBER,
    BOARD_ID NUMBER NOT NULL,
    MEMBER_ID NUMBER NOT NULL,
    CONTENT VARCHAR2(1000 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP (6),
    CONSTRAINT PK_BOARD_COMMENT PRIMARY KEY (COMMENT_ID)
);

CREATE TABLE BOARD_IMAGE (
    IMAGE_ID NUMBER,
    BOARD_ID NUMBER NOT NULL,
    ORIGINAL_NAME VARCHAR2(300 CHAR),
    SAVED_NAME VARCHAR2(300 CHAR),
    IMAGE_URL VARCHAR2(1000 CHAR),
    CREATED_AT TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL,
    LINK_URL VARCHAR2(1000 CHAR),
    CONSTRAINT PK_BOARD_IMAGE PRIMARY KEY (IMAGE_ID)
);

CREATE TABLE BOARD_VIEW_HISTORY (
    BOARD_ID NUMBER NOT NULL,
    MEMBER_ID NUMBER NOT NULL,
    VIEWED_AT TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_BOARD_VIEW_HISTORY PRIMARY KEY (BOARD_ID, MEMBER_ID)
);


/* 3. 외래키 */

ALTER TABLE BOARD
    ADD CONSTRAINT FK_BOARD_MEMBER
    FOREIGN KEY (MEMBER_ID)
    REFERENCES APP_MEMBER (MEMBER_ID)
    ON DELETE CASCADE;

ALTER TABLE BOARD
    ADD CONSTRAINT FK_BOARD_ANIMAL
    FOREIGN KEY (ANIMAL_ID)
    REFERENCES ANIMAL_TYPE (ANIMAL_ID);

ALTER TABLE BOARD_COMMENT
    ADD CONSTRAINT FK_COMMENT_BOARD
    FOREIGN KEY (BOARD_ID)
    REFERENCES BOARD (BOARD_ID)
    ON DELETE CASCADE;

ALTER TABLE BOARD_COMMENT
    ADD CONSTRAINT FK_COMMENT_MEMBER
    FOREIGN KEY (MEMBER_ID)
    REFERENCES APP_MEMBER (MEMBER_ID)
    ON DELETE CASCADE;

ALTER TABLE BOARD_IMAGE
    ADD CONSTRAINT FK_IMAGE_BOARD
    FOREIGN KEY (BOARD_ID)
    REFERENCES BOARD (BOARD_ID)
    ON DELETE CASCADE;

ALTER TABLE BOARD_VIEW_HISTORY
    ADD CONSTRAINT FK_BOARD_VIEW_HISTORY_BOARD
    FOREIGN KEY (BOARD_ID)
    REFERENCES BOARD (BOARD_ID)
    ON DELETE CASCADE;

ALTER TABLE BOARD_VIEW_HISTORY
    ADD CONSTRAINT FK_BOARD_VIEW_HISTORY_MEMBER
    FOREIGN KEY (MEMBER_ID)
    REFERENCES APP_MEMBER (MEMBER_ID)
    ON DELETE CASCADE;


/* 5. 설명 */

COMMENT ON TABLE BOARD_VIEW_HISTORY IS '게시글 회원별 조회 이력';

COMMENT ON COLUMN BOARD_VIEW_HISTORY.BOARD_ID IS '게시글 번호';

COMMENT ON COLUMN BOARD_VIEW_HISTORY.MEMBER_ID IS '조회한 회원 번호';

COMMENT ON COLUMN BOARD_VIEW_HISTORY.VIEWED_AT IS '최초 조회일';


COMMIT;
