/* =============================================================
   BOARD 더미 데이터 정리본 (Oracle)

   기준
   - petcity-common.zip의 BoardMapper.xml 확인
   - BOARD_ID는 Mapper와 동일하게 SEQ_BOARD.NEXTVAL 사용
   - 동일 제목으로 반복 입력된 펫도감 게시글은 최초 1건만 유지
   - 기존 146건에서 중복 25건 제거
   - 최종 121건
   - 특정 Oracle 사용자명 또는 스키마 접두어를 사용하지 않음

   선행 조건
   - APP_MEMBER, ANIMAL_TYPE, BOARD 테이블 존재
   - 00_BOARD 데이터 초기화 및 시퀀스 재생성.sql 선행 실행
============================================================= */

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'NOTICE','PetCity 공지사항 테스트',5,TIMESTAMP '2026-07-09 15:12:17',TIMESTAMP '2026-07-15 11:25:15',NULL,TO_CLOB('<p>ㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇ</p><p><br></p><p>ㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇ</p><p>ㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇ</p><p>ㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇ</p><p>ㄹㅇㄴㄹㅇㄴㄻㄹㄴㅇㅁㄻㄴㅇ</p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test004'),'QNA','강아지가 밥을 잘 안 먹어요',9,TIMESTAMP '2026-07-09 15:12:19',NULL,9,TO_CLOB('강아지가 어제부터 밥을 잘 안 먹는데 병원에 가야 할까요?')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test005'),'FREE','우리 강아지 산책 다녀왔어요',12,TIMESTAMP '2026-07-09 15:12:22',NULL,NULL,TO_CLOB('오늘 날씨가 좋아서 강아지랑 산책을 다녀왔습니다.')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'INFO','fdfd',0,TIMESTAMP '2026-07-10 11:14:11',NULL,7,TO_CLOB('fdfdf')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'NOTICE','ㄹㅇ',11,TIMESTAMP '2026-07-10 14:34:49',NULL,NULL,TO_CLOB('공지다')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test020'),'QNA','ㄹㅇㄴㄹㅇㅁㄴㄹ',5,TIMESTAMP '2026-07-10 15:04:28',NULL,8,TO_CLOB('<p>ㄴㅁㅇㄹㄴㅁㄹㄴㅁㄹ<img src="/upload/board/editor/17fd84de-5b51-42a4-942a-e82628f2a921.png" style="width: 738px;"></p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test021'),'QNA','fdfdf',5,TIMESTAMP '2026-07-10 15:05:21',NULL,6,TO_CLOB('<p>fdfdfd</p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'INFO','ㄹㅇㄴㅁㄹ',1,TIMESTAMP '2026-07-10 15:18:08',NULL,8,TO_CLOB('<p>ㄴㅁㅇㄹㄴㅁㅇㄹ</p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test023'),'FREE','asdfsa',2,TIMESTAMP '2026-07-10 15:18:57',NULL,6,TO_CLOB('<p>sadfdsaf</p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test024'),'FREE','ㄹㄴㅇㅁㄹ',8,TIMESTAMP '2026-07-10 16:15:12',NULL,13,TO_CLOB('<p>ㄴㅇㅇㅁㄹㅇㄴㅁㄹ<img src="/upload/board/editor/bff95861-7e74-4425-a37a-139cc7974f8e.png" style="width: 738px;"></p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test027'),'FREE','[페이징테스트] 자유게시판 더미 글 01',3,TIMESTAMP '2026-07-13 16:08:10',TIMESTAMP '2026-07-13 16:08:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 1')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test028'),'FREE','[페이징테스트] 자유게시판 더미 글 02',6,TIMESTAMP '2026-07-13 16:09:10',TIMESTAMP '2026-07-13 16:09:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 2')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test029'),'FREE','[페이징테스트] 강아지 산책 이야기 03',9,TIMESTAMP '2026-07-13 16:10:10',TIMESTAMP '2026-07-13 16:10:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 3')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test030'),'FREE','[페이징테스트] 자유게시판 더미 글 04',12,TIMESTAMP '2026-07-13 16:11:10',TIMESTAMP '2026-07-13 16:11:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 4')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test031'),'FREE','[페이징테스트] 고양이 자랑 05',15,TIMESTAMP '2026-07-13 16:12:10',TIMESTAMP '2026-07-13 16:12:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 5')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test032'),'FREE','[페이징테스트] 강아지 산책 이야기 06',18,TIMESTAMP '2026-07-13 16:13:10',TIMESTAMP '2026-07-13 16:13:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 6')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test033'),'FREE','[페이징테스트] 자유게시판 더미 글 07',21,TIMESTAMP '2026-07-13 16:14:10',TIMESTAMP '2026-07-13 16:14:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 7')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test034'),'FREE','[페이징테스트] 자유게시판 더미 글 08',24,TIMESTAMP '2026-07-13 16:15:10',TIMESTAMP '2026-07-13 16:15:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 8')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test035'),'FREE','[페이징테스트] 강아지 산책 이야기 09',27,TIMESTAMP '2026-07-13 16:16:10',TIMESTAMP '2026-07-13 16:16:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 9')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test036'),'FREE','[페이징테스트] 고양이 자랑 10',30,TIMESTAMP '2026-07-13 16:17:10',TIMESTAMP '2026-07-13 16:17:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 10')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test037'),'FREE','[페이징테스트] 자유게시판 더미 글 11',33,TIMESTAMP '2026-07-13 16:18:10',TIMESTAMP '2026-07-13 16:18:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 11')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test038'),'FREE','[페이징테스트] 강아지 산책 이야기 12',36,TIMESTAMP '2026-07-13 16:19:10',TIMESTAMP '2026-07-13 16:19:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 12')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test039'),'FREE','[페이징테스트] 자유게시판 더미 글 13',39,TIMESTAMP '2026-07-13 16:20:10',TIMESTAMP '2026-07-13 16:20:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 13')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test040'),'FREE','[페이징테스트] 자유게시판 더미 글 14',42,TIMESTAMP '2026-07-13 16:21:10',TIMESTAMP '2026-07-13 16:21:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 14')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test041'),'FREE','[페이징테스트] 강아지 산책 이야기 15',45,TIMESTAMP '2026-07-13 16:22:10',TIMESTAMP '2026-07-13 16:22:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 15')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test042'),'FREE','[페이징테스트] 자유게시판 더미 글 16',48,TIMESTAMP '2026-07-13 16:23:10',TIMESTAMP '2026-07-13 16:23:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 16')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test043'),'FREE','[페이징테스트] 자유게시판 더미 글 17',51,TIMESTAMP '2026-07-13 16:24:10',TIMESTAMP '2026-07-13 16:24:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 17')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test044'),'FREE','[페이징테스트] 강아지 산책 이야기 18',54,TIMESTAMP '2026-07-13 16:25:10',TIMESTAMP '2026-07-13 16:25:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 18')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test045'),'FREE','[페이징테스트] 자유게시판 더미 글 19',57,TIMESTAMP '2026-07-13 16:26:10',TIMESTAMP '2026-07-13 16:26:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 19')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test046'),'FREE','[페이징테스트] 고양이 자랑 20',60,TIMESTAMP '2026-07-13 16:27:10',TIMESTAMP '2026-07-13 16:27:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 20')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test047'),'FREE','[페이징테스트] 강아지 산책 이야기 21',63,TIMESTAMP '2026-07-13 16:28:10',TIMESTAMP '2026-07-13 16:28:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 21')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test048'),'FREE','[페이징테스트] 자유게시판 더미 글 22',66,TIMESTAMP '2026-07-13 16:29:10',TIMESTAMP '2026-07-13 16:29:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 22')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test049'),'FREE','[페이징테스트] 자유게시판 더미 글 23',69,TIMESTAMP '2026-07-13 16:30:10',TIMESTAMP '2026-07-13 16:30:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 23')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test050'),'FREE','[페이징테스트] 강아지 산책 이야기 24',72,TIMESTAMP '2026-07-13 16:31:10',TIMESTAMP '2026-07-13 16:31:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 24')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test051'),'FREE','[페이징테스트] 고양이 자랑 25',75,TIMESTAMP '2026-07-13 16:32:10',TIMESTAMP '2026-07-13 16:32:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 25')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test052'),'FREE','[페이징테스트] 자유게시판 더미 글 26',78,TIMESTAMP '2026-07-13 16:33:10',TIMESTAMP '2026-07-13 16:33:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 26')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test053'),'FREE','[페이징테스트] 강아지 산책 이야기 27',81,TIMESTAMP '2026-07-13 16:34:10',TIMESTAMP '2026-07-13 16:34:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 27')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test054'),'FREE','[페이징테스트] 자유게시판 더미 글 28',84,TIMESTAMP '2026-07-13 16:35:10',TIMESTAMP '2026-07-13 16:35:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 28')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test055'),'FREE','[페이징테스트] 자유게시판 더미 글 29',87,TIMESTAMP '2026-07-13 16:36:10',TIMESTAMP '2026-07-13 16:36:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 29')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test056'),'FREE','[페이징테스트] 강아지 산책 이야기 30',90,TIMESTAMP '2026-07-13 16:37:10',TIMESTAMP '2026-07-13 16:37:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 30')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test057'),'FREE','[페이징테스트] 자유게시판 더미 글 31',93,TIMESTAMP '2026-07-13 16:38:10',TIMESTAMP '2026-07-13 16:38:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 31')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test058'),'FREE','[페이징테스트] 자유게시판 더미 글 32',96,TIMESTAMP '2026-07-13 16:39:10',TIMESTAMP '2026-07-13 16:39:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 32')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test059'),'FREE','[페이징테스트] 강아지 산책 이야기 33',99,TIMESTAMP '2026-07-13 16:40:10',TIMESTAMP '2026-07-13 16:40:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 33')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test060'),'FREE','[페이징테스트] 자유게시판 더미 글 34',2,TIMESTAMP '2026-07-13 16:41:10',TIMESTAMP '2026-07-13 16:41:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 34')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test061'),'FREE','[페이징테스트] 고양이 자랑 35',5,TIMESTAMP '2026-07-13 16:42:10',TIMESTAMP '2026-07-13 16:42:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 35')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test062'),'FREE','[페이징테스트] 강아지 산책 이야기 36',8,TIMESTAMP '2026-07-13 16:43:10',TIMESTAMP '2026-07-13 16:43:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 36')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test063'),'FREE','[페이징테스트] 자유게시판 더미 글 37',11,TIMESTAMP '2026-07-13 16:44:10',TIMESTAMP '2026-07-13 16:44:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 37')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test064'),'FREE','[페이징테스트] 자유게시판 더미 글 38',14,TIMESTAMP '2026-07-13 16:45:10',TIMESTAMP '2026-07-13 16:45:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 38')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test065'),'FREE','[페이징테스트] 강아지 산책 이야기 39',17,TIMESTAMP '2026-07-13 16:46:10',TIMESTAMP '2026-07-13 16:46:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 39')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test066'),'FREE','[페이징테스트] 고양이 자랑 40',20,TIMESTAMP '2026-07-13 16:47:10',TIMESTAMP '2026-07-13 16:47:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 40')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test067'),'FREE','[페이징테스트] 자유게시판 더미 글 41',23,TIMESTAMP '2026-07-13 16:48:10',TIMESTAMP '2026-07-13 16:48:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 41')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test068'),'FREE','[페이징테스트] 강아지 산책 이야기 42',26,TIMESTAMP '2026-07-13 16:49:10',TIMESTAMP '2026-07-13 16:49:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 42')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test069'),'FREE','[페이징테스트] 자유게시판 더미 글 43',29,TIMESTAMP '2026-07-13 16:50:10',TIMESTAMP '2026-07-13 16:50:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 43')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test070'),'FREE','[페이징테스트] 자유게시판 더미 글 44',32,TIMESTAMP '2026-07-13 16:51:10',TIMESTAMP '2026-07-13 16:51:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 44')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test071'),'FREE','[페이징테스트] 강아지 산책 이야기 45',35,TIMESTAMP '2026-07-13 16:52:10',TIMESTAMP '2026-07-13 16:52:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 45')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test072'),'FREE','[페이징테스트] 자유게시판 더미 글 46',38,TIMESTAMP '2026-07-13 16:53:10',TIMESTAMP '2026-07-13 16:53:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 46')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test073'),'FREE','[페이징테스트] 자유게시판 더미 글 47',41,TIMESTAMP '2026-07-13 16:54:10',TIMESTAMP '2026-07-13 16:54:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 47')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test074'),'FREE','[페이징테스트] 강아지 산책 이야기 48',44,TIMESTAMP '2026-07-13 16:55:10',TIMESTAMP '2026-07-13 16:55:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 48')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test075'),'FREE','[페이징테스트] 자유게시판 더미 글 49',47,TIMESTAMP '2026-07-13 16:56:10',TIMESTAMP '2026-07-13 16:56:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 49')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test076'),'FREE','[페이징테스트] 고양이 자랑 50',50,TIMESTAMP '2026-07-13 16:57:10',TIMESTAMP '2026-07-13 16:57:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 50')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test077'),'FREE','[페이징테스트] 강아지 산책 이야기 51',53,TIMESTAMP '2026-07-13 16:58:10',TIMESTAMP '2026-07-13 16:58:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 51')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test078'),'FREE','[페이징테스트] 자유게시판 더미 글 52',56,TIMESTAMP '2026-07-13 16:59:10',TIMESTAMP '2026-07-13 16:59:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 52')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test079'),'FREE','[페이징테스트] 자유게시판 더미 글 53',59,TIMESTAMP '2026-07-13 17:00:10',TIMESTAMP '2026-07-13 17:00:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 53')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test080'),'FREE','[페이징테스트] 강아지 산책 이야기 54',62,TIMESTAMP '2026-07-13 17:01:10',TIMESTAMP '2026-07-13 17:01:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 54')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test081'),'FREE','[페이징테스트] 고양이 자랑 55',65,TIMESTAMP '2026-07-13 17:02:10',TIMESTAMP '2026-07-13 17:02:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 55')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test082'),'FREE','[페이징테스트] 자유게시판 더미 글 56',70,TIMESTAMP '2026-07-13 17:03:10',TIMESTAMP '2026-07-13 17:03:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 56')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test083'),'FREE','[페이징테스트] 강아지 산책 이야기 57',73,TIMESTAMP '2026-07-13 17:04:10',TIMESTAMP '2026-07-13 17:04:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 57')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test084'),'FREE','[페이징테스트] 자유게시판 더미 글 58',75,TIMESTAMP '2026-07-13 17:05:10',TIMESTAMP '2026-07-13 17:05:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 58')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test085'),'FREE','[페이징테스트] 자유게시판 더미 글 59',80,TIMESTAMP '2026-07-13 17:06:10',TIMESTAMP '2026-07-13 17:06:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 59')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test088'),'FREE','[페이징테스트] 자유게시판 더미 글 62',88,TIMESTAMP '2026-07-13 17:09:10',TIMESTAMP '2026-07-13 17:09:10',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 62')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test089'),'FREE','[페이징테스트] 강아지 산책 이야기 63',95,TIMESTAMP '2026-07-13 17:10:10',TIMESTAMP '2026-07-13 17:10:10',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 63')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'FAQ','회원가입을 하지 않아도 동물병원을 검색할 수 있나요?',0,TIMESTAMP '2026-07-14 09:56:06',NULL,NULL,TO_CLOB('
            <p>네. 동물병원 목록 조회와 기본 검색은 로그인하지 않아도 이용할 수 있습니다.</p>
            <p>다만 병원 즐겨찾기, 리뷰 작성, 반려동물 정보 관리 같은 회원 전용 기능은 로그인이 필요합니다.</p>
        ')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'FAQ','현재 위치를 불러오지 못할 때는 어떻게 해야 하나요?',0,TIMESTAMP '2026-07-14 09:56:06',NULL,NULL,TO_CLOB('
            <p>브라우저 주소창 옆의 위치 권한을 확인하고 PetCity의 위치 접근을 허용해 주세요.</p>
            <p>위치 권한을 허용하지 않아도 지역이나 병원 이름을 직접 검색해 병원을 찾을 수 있습니다.</p>
        ')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'FAQ','병원과의 거리는 어떤 기준으로 계산되나요?',0,TIMESTAMP '2026-07-14 09:56:06',NULL,NULL,TO_CLOB('
            <p>사용자의 현재 위치 좌표와 병원 좌표를 기준으로 거리를 계산합니다.</p>
            <p>표시되는 거리는 실제 도로 이동 거리와 다를 수 있으므로 참고용으로 이용해 주세요.</p>
        ')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'FAQ','영업 중으로 표시된 병원은 바로 방문해도 되나요?',0,TIMESTAMP '2026-07-14 09:56:06',NULL,NULL,TO_CLOB('
            <p>영업 상태는 등록된 영업시간 정보를 기준으로 표시됩니다.</p>
            <p>공휴일, 임시휴무, 진료 일정 변경이 반영되지 않았을 수 있으므로 방문 전 병원에 전화로 확인하는 것을 권장합니다.</p>
        ')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'FAQ','병원 정보가 실제 정보와 다르게 표시됩니다.',0,TIMESTAMP '2026-07-14 09:56:06',NULL,NULL,TO_CLOB('
            <p>병원 정보는 공공데이터와 병원에서 제공한 정보를 바탕으로 표시됩니다.</p>
            <p>이전, 폐업, 전화번호 변경처럼 실제 정보와 다른 내용이 있다면 관리자에게 알려 주세요. 확인 후 수정하겠습니다.</p>
        ')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'FAQ','파충류나 조류 같은 특수동물 진료 병원은 어떻게 찾나요?',0,TIMESTAMP '2026-07-14 09:56:06',NULL,NULL,TO_CLOB('
            <p>병원 검색 화면에서 진료 동물 종류를 파충류, 조류, 소동물 등으로 선택해 검색해 주세요.</p>
            <p>병원마다 실제 진료 가능 동물과 진료 일정이 다를 수 있으므로 방문 전 전화 문의가 필요합니다.</p>
        ')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'FAQ','병원을 즐겨찾기에 저장하려면 어떻게 해야 하나요?',0,TIMESTAMP '2026-07-14 09:56:06',NULL,NULL,TO_CLOB('
            <p>로그인 후 병원 목록이나 상세 화면의 하트 모양 즐겨찾기 버튼을 눌러 주세요.</p>
            <p>저장한 병원은 마이페이지의 즐겨찾기 목록에서 다시 확인할 수 있습니다.</p>
        ')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'FAQ','병원 리뷰는 누구나 작성할 수 있나요?',0,TIMESTAMP '2026-07-14 09:56:06',NULL,NULL,TO_CLOB('
            <p>리뷰를 작성하려면 PetCity 회원으로 로그인해야 합니다.</p>
            <p>다른 이용자에게 도움이 될 수 있도록 실제 이용 경험을 바탕으로 작성해 주세요.</p>
        ')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'FAQ','작성한 리뷰를 수정하거나 삭제할 수 있나요?',0,TIMESTAMP '2026-07-14 09:56:06',NULL,NULL,TO_CLOB('
            <p>본인이 작성한 리뷰는 수정하거나 삭제할 수 있습니다.</p>
            <p>욕설, 광고, 개인정보 노출 등 운영정책에 위반되는 리뷰는 관리자에 의해 제한될 수 있습니다.</p>
        ')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'FAQ','수의사상담 게시판은 어떻게 이용하나요?',0,TIMESTAMP '2026-07-14 09:56:06',NULL,NULL,TO_CLOB('
            <p>수의사상담 게시판에서 반려동물 종류와 증상을 작성해 질문을 등록할 수 있습니다.</p>
            <p>등록된 질문에는 병원장 권한을 가진 회원이나 관리자가 답변할 수 있습니다.</p>
        ')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'FAQ','수의사상담 답변만 보고 병원에 가지 않아도 되나요?',0,TIMESTAMP '2026-07-14 09:56:06',NULL,NULL,TO_CLOB('
            <p>수의사상담 게시판의 답변은 일반적인 참고 정보이며, 직접적인 진단이나 처방을 대신할 수 없습니다.</p>
            <p>증상이 지속되거나 상태가 심각하다면 가까운 동물병원에서 직접 진료를 받아 주세요.</p>
        ')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'FAQ','반려동물이 응급상황일 때 상담 게시판을 이용해도 되나요?',0,TIMESTAMP '2026-07-14 09:56:06',NULL,NULL,TO_CLOB('
            <p>호흡곤란, 심한 출혈, 경련, 의식 저하, 독성물질 섭취 같은 응급상황에서는 게시판 답변을 기다리면 안 됩니다.</p>
            <p>즉시 가까운 응급 진료 가능 동물병원에 전화한 뒤 방문해 주세요.</p>
        ')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'FAQ','병원장 권한은 어떻게 신청하나요?',0,TIMESTAMP '2026-07-14 09:56:06',NULL,NULL,TO_CLOB('
            <p>로그인 후 병원장 권한 신청 화면에서 담당 병원을 선택하고 필요한 정보를 입력해 주세요.</p>
            <p>관리자가 제출된 내용을 확인하고 승인하면 병원장 권한을 사용할 수 있습니다.</p>
        ')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'FAQ','내 반려동물 정보는 어디에서 등록하나요?',0,TIMESTAMP '2026-07-14 09:56:06',NULL,NULL,TO_CLOB('
            <p>로그인 후 마이페이지의 반려동물 관리 메뉴에서 이름, 종류, 성별, 생년월일, 체중 등의 정보를 등록할 수 있습니다.</p>
            <p>등록된 정보는 마이페이지에서 수정하거나 삭제할 수 있습니다.</p>
        ')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'FAQ','회원탈퇴를 하면 작성한 게시글과 댓글은 어떻게 되나요?',0,TIMESTAMP '2026-07-14 09:56:06',TIMESTAMP '2026-07-30 13:44:53',NULL,TO_CLOB('            <p>회원탈퇴 시 회원 계정과 연결된 게시글, 댓글 등 일부 작성 정보가 함께 삭제될 수 있습니다.</p>
            <p>탈퇴 전 보관이 필요한 내용이 있다면 미리 확인해 주세요.</p>
        ')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test112'),'QNA','ㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹㅁㄴㅇㄹ',2,TIMESTAMP '2026-07-15 11:11:10',NULL,22,(TO_CLOB('<p>ㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹ') || TO_CLOB('ㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁ'))||(TO_CLOB('ㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㄹㅇㅁㄴㄹㅇㄴㅁㄹㅇㄴㅁㄹㅇㄴ') || TO_CLOB('ㅁㄹㄹ</p>'))
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'NOTICE','공지',3,TIMESTAMP '2026-07-21 09:48:31',NULL,NULL,TO_CLOB('내가 공지')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'NOTICE','fd',3,TIMESTAMP '2026-07-21 09:59:11',NULL,NULL,TO_CLOB('fdfdf')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'INFO','fdsfsdf',0,TIMESTAMP '2026-07-21 17:05:33',NULL,6,TO_CLOB('fsdafdsafasdf')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test118'),'QNA','개개ㅐㅐ',2,TIMESTAMP '2026-07-22 11:56:24',NULL,7,TO_CLOB('아라ㅣㄴ어ㅏㅣ럼ㄴ이ㅏㄹ')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'INFO','fdf',0,TIMESTAMP '2026-07-24 10:51:45',NULL,8,TO_CLOB('<p>fdfdfdf<img src="/upload/board/editor/72925fb9-0819-48bc-b6e1-185f53e600d7.png" style="width: 734px;"></p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'INFO','fasdfafds',0,TIMESTAMP '2026-07-24 14:02:28',NULL,6,TO_CLOB('<p>fasdf<img src="/upload/board/editor/522dc549-b36a-450d-b10f-bf50f477c6ea.png" style="width: 734px;"></p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'INFO','fdsaf',0,TIMESTAMP '2026-07-24 14:03:02',NULL,23,TO_CLOB('<p>asdfsafasdf<img src="/upload/board/editor/033a9b82-f080-4203-8b00-6f87d96b6820.jpg" style="width: 734px;"></p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test144'),'FREE','[페이징테스트] 강아지 산책 이야기 60',80,TIMESTAMP '2026-07-22 19:41:57.167883',TIMESTAMP '2026-07-22 19:41:57.167883',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 60')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test145'),'FREE','[페이징테스트] 자유게시판 더미 글 61',83,TIMESTAMP '2026-07-22 19:42:57.167927',TIMESTAMP '2026-07-22 19:42:57.167927',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 61')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test148'),'FREE','[페이징테스트] 자유게시판 더미 글 64',92,TIMESTAMP '2026-07-22 19:45:57.168144',TIMESTAMP '2026-07-22 19:45:57.168144',6,TO_CLOB('페이징 테스트를 위한 강아지 관련 더미 내용입니다. 번호: 64')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test149'),'FREE','[페이징테스트] 고양이 자랑 65',95,TIMESTAMP '2026-07-22 19:46:57.168227',TIMESTAMP '2026-07-22 19:46:57.168227',6,TO_CLOB('페이징 테스트를 위한 반려동물 자유토크 내용입니다. 번호: 65')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'INFO','fasd',0,TIMESTAMP '2026-07-24 15:56:24',NULL,6,TO_CLOB('asdf')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test004'),'QNA','fdsfdsf',3,TIMESTAMP '2026-07-24 16:25:52',NULL,12,TO_CLOB('fsdafsdafsadfasfsdaf')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'INFO','fdsfsdafsadf',0,TIMESTAMP '2026-07-24 18:06:50',NULL,8,TO_CLOB('<p>fasdfsafsdafsdafsadfdsafsadf<img src="/upload/board/editor/d56eef82-0b40-469a-bdc4-9d8e177786d6.png" style="width: 716px;"></p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test006'),'FREE','응가',1,TIMESTAMP '2026-07-27 09:04:30',NULL,6,TO_CLOB('시발')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test007'),'QNA','ㄹ안머라ㅣㄴ머라ㅣㄴㅁ얼',1,TIMESTAMP '2026-07-27 16:45:34',NULL,8,TO_CLOB('<p>란ㅇ머라ㅣㅓㅁㄴ랴ㅓ미ㅏㅜ리ㅏㄴㅇㅍㄴㅇㅁㅍㄴㅇㅁㄹㅇㄴㄹ<img src="/upload/board/editor/f32f4e8d-bef5-42b3-86fb-90b18b35d84d.png" style="width: 716px;">ㄹㅇㄴㄹㅇㄴㄹㄴㅁㄹㄴㅇㅁㄻㄴㅇㄻㄴㅇㄹㄹㅇㄴㅁㄹ</p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'NOTICE','fsdafsaffsdafsaffsdafsaffsdafsaffsdafsaffsdafsaffsdafsaffsdafsaffsdafsaffsdafsaffsdafsaffsdafsaffsda',2,TIMESTAMP '2026-07-28 10:48:09',NULL,NULL,TO_CLOB('<p>fdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsdafdsaffsda<img src="/upload/board/editor/300dc8fe-e687-4955-9506-f8827c37e37b.jpg" style="width: 715.851px;">dfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssd')||TO_CLOB('fdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssssdfdsfsdffdssssssssssssssssssssss</p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test009'),'QNA','fsdafsadf',1,TIMESTAMP '2026-07-28 10:50:55',NULL,12,TO_CLOB('<p>fdsafasdf<img src="/upload/board/editor/8df78571-e96f-46b2-9d29-7603e0e0311b.png" style="width: 716px;"></p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'INFO','[펫도감 더미] 말티즈 눈물자국 관리 방법',128,TIMESTAMP '2026-07-27 11:43:45',TIMESTAMP '2026-07-27 11:43:45',6,TO_CLOB('<h2>말티즈 눈물자국, 생활 관리부터 시작해요</h2><p>눈 주변은 미지근한 물에 적신 부드러운 거즈로 닦고, 물기를 충분히 말려 주세요.</p><p>눈곱의 색이나 양이 갑자기 달라졌다면 자가 처치보다 동물병원 상담을 권장합니다.</p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'INFO','[펫도감 더미] 골든리트리버 산책량과 관절 관리',95,TIMESTAMP '2026-07-24 11:43:46',TIMESTAMP '2026-07-24 11:43:46',8,TO_CLOB('<h2>활동량이 많은 대형견의 건강 루틴</h2><p>산책 전후로 가벼운 스트레칭 시간을 만들고, 더운 날에는 낮 시간을 피해 주세요.</p><p>절뚝거림이나 활동량 감소가 계속되면 관절 검진이 필요할 수 있습니다.</p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'INFO','[펫도감 더미] 보더콜리의 지루함 줄이는 놀이 5가지',76,TIMESTAMP '2026-07-20 11:43:46',TIMESTAMP '2026-07-20 11:43:46',9,TO_CLOB('<h2>똑똑한 반려견에게는 두뇌 활동도 필요해요</h2><p>노즈워크, 간단한 트릭 연습, 숨은 장난감 찾기를 짧게 나누어 진행해 보세요.</p><p>한 번에 오래 하기보다 매일 꾸준히 하는 것이 좋습니다.</p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'INFO','[펫도감 더미] 코리안숏헤어, 실내 생활 환경 만들기',143,TIMESTAMP '2026-07-28 11:43:46',TIMESTAMP '2026-07-28 11:43:46',14,TO_CLOB('<h2>고양이가 편안한 집은 높은 공간에서 시작돼요</h2><p>캣타워나 선반처럼 안전하게 올라갈 수 있는 공간과 숨을 곳을 마련해 주세요.</p><p>화장실은 조용한 곳에 두고 매일 청결하게 관리하는 것이 좋습니다.</p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'INFO','[펫도감 더미] 먼치킨 체형에 맞는 생활 안전 수칙',84,TIMESTAMP '2026-07-22 11:43:46',TIMESTAMP '2026-07-22 11:43:46',16,TO_CLOB('<h2>낮은 높이의 계단과 미끄럼 방지가 중요해요</h2><p>소파와 침대 주변에는 반려동물 계단을 두고, 자주 뛰어내리는 곳에는 미끄럼 방지 매트를 깔아 주세요.</p><p>걷는 모습이 평소와 다르다면 빠르게 병원에 문의하세요.</p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'INFO','[펫도감 더미] 러시안블루와 조용한 교감 시간',67,TIMESTAMP '2026-07-17 11:43:46',TIMESTAMP '2026-07-17 11:43:46',18,TO_CLOB('<h2>낯선 환경에서는 먼저 기다려 주세요</h2><p>고양이가 스스로 다가올 때까지 낮은 목소리로 말을 걸고, 짧은 놀이로 관계를 만들어 보세요.</p><p>억지로 안거나 숨는 공간을 막는 행동은 피해주세요.</p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'INFO','[펫도감 더미] 도마뱀 사육장 온도와 습도 체크',58,TIMESTAMP '2026-07-25 11:43:46',TIMESTAMP '2026-07-25 11:43:46',22,TO_CLOB('<h2>종마다 다른 적정 환경을 먼저 확인하세요</h2><p>온도계와 습도계를 사육장 양쪽에 설치하면 환경 변화를 더 쉽게 확인할 수 있습니다.</p><p>먹이 섭취량이나 탈피 상태가 달라질 때는 사육 환경을 함께 점검해 주세요.</p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'INFO','[펫도감 더미] 거북이 수질 관리와 일광욕 공간',46,TIMESTAMP '2026-07-18 11:43:46',TIMESTAMP '2026-07-18 11:43:46',23,TO_CLOB('<h2>깨끗한 물과 쉴 수 있는 육지 공간을 함께</h2><p>먹이 찌꺼기는 바로 제거하고, 여과기 상태와 물 온도를 정기적으로 확인해 주세요.</p><p>종에 맞는 UVB 조명과 안전한 일광욕 공간도 필요합니다.</p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'INFO','[펫도감 더미] 햄스터 케이지 청소 주기와 방법',112,TIMESTAMP '2026-07-26 11:43:46',TIMESTAMP '2026-07-26 11:43:46',29,TO_CLOB('<h2>집 전체를 한 번에 바꾸지 않아도 돼요</h2><p>매일 젖은 깔짚과 먹이 찌꺼기를 제거하고, 전체 청소는 케이지 상태에 맞춰 진행하세요.</p><p>기존 둥지 재료를 일부 남겨두면 환경 변화 스트레스를 줄이는 데 도움이 됩니다.</p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'INFO','[펫도감 더미] 토끼가 먹으면 안 되는 음식 정리',91,TIMESTAMP '2026-07-23 11:43:46',TIMESTAMP '2026-07-23 11:43:46',30,TO_CLOB('<h2>건초는 기본, 간식은 소량만</h2><p>토끼는 충분한 양의 건초와 깨끗한 물이 필요합니다. 새로운 채소는 아주 적은 양부터 반응을 살펴보며 급여하세요.</p><p>식욕이 줄거나 배변량이 달라졌다면 빠른 진료가 필요할 수 있습니다.</p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'INFO','[펫도감 더미] 친칠라 모래목욕, 이렇게 준비하세요',52,TIMESTAMP '2026-07-16 11:43:46',TIMESTAMP '2026-07-16 11:43:46',31,TO_CLOB('<h2>친칠라 전용 모래를 짧은 시간 제공해요</h2><p>습기에 약한 친칠라는 물목욕 대신 전용 모래목욕이 필요합니다.</p><p>모래가 더러워지면 교체하고, 목욕통은 사용 후 치워두어 과도한 목욕을 예방해 주세요.</p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'INFO','[펫도감 더미] 금붕어 어항 물갈이의 기본',73,TIMESTAMP '2026-07-21 11:43:46',TIMESTAMP '2026-07-21 11:43:46',33,TO_CLOB('<h2>한 번에 전부 바꾸기보다 부분 환수가 좋아요</h2><p>새 물은 수온을 맞추고 염소 제거제를 사용한 뒤, 기존 물과 조금씩 섞어 주세요.</p><p>먹이는 1~2분 안에 먹을 양만 급여해 수질 오염을 줄입니다.</p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'INFO','[펫도감 더미] 열대어 합사 전 확인해야 할 3가지',64,TIMESTAMP '2026-07-19 11:43:46',TIMESTAMP '2026-07-19 11:43:46',35,TO_CLOB('<h2>수온, 성격, 크기를 먼저 비교하세요</h2><p>같은 수조에 넣기 전 적정 수온과 수질 조건이 비슷한지 확인해야 합니다.</p><p>새 개체는 가능하면 별도 공간에서 상태를 확인한 뒤 합사하는 것이 안전합니다.</p>')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test049'),'FREE','zzzz',2,TIMESTAMP '2026-07-30 13:15:59',NULL,6,TO_CLOB('zzzzz')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'test050'),'QNA','saddfasdf',1,TIMESTAMP '2026-07-30 13:16:44',NULL,11,TO_CLOB('asdfsafsdaf')
FROM DUAL;

INSERT INTO BOARD (BOARD_ID,MEMBER_ID,BOARD_TYPE,TITLE,HIT,CREATED_AT,UPDATED_AT,ANIMAL_ID,CONTENT)
SELECT
SEQ_BOARD.NEXTVAL,(SELECT MEMBER_ID FROM APP_MEMBER WHERE LOGIN_ID = 'admin'),'NOTICE','123213',1,TIMESTAMP '2026-07-30 13:17:29',NULL,NULL,TO_CLOB('312132')
FROM DUAL;

COMMIT;

SELECT COUNT(*) AS BOARD_COUNT,
       MIN(BOARD_ID) AS MIN_BOARD_ID,
       MAX(BOARD_ID) AS MAX_BOARD_ID
FROM BOARD;
