/* 선행 실행: 01-00, 07-00, 07-01 */

INSERT INTO BOARD_COMMENT (
    COMMENT_ID, BOARD_ID, MEMBER_ID, CONTENT, CREATED_AT, UPDATED_AT
)
WITH COMMENT_DATA (
    BOARD_TYPE, BOARD_TITLE, BOARD_WRITER_LOGIN,
    COMMENT_WRITER_LOGIN, CONTENT, CREATED_AT, UPDATED_AT
) AS (
    SELECT 'NOTICE', 'PetCity 공지사항 테스트', 'admin', 'admin',
           'ㄹ', TIMESTAMP '2026-07-13 16:09:26', CAST(NULL AS TIMESTAMP) FROM DUAL
    UNION ALL SELECT 'QNA', '강아지가 밥을 잘 안 먹어요', 'test004', 'admin',
           'ㄹㅇㄴㄹㄴㅇㅁㄻㄹㅇㄹㅇ류ㅠㅠ', TIMESTAMP '2026-07-15 10:05:43', TIMESTAMP '2026-07-15 10:05:49' FROM DUAL
    UNION ALL SELECT 'FREE', '우리 강아지 산책 다녀왔어요', 'test005', 'admin',
           'ㄹㅇㄴㄹㅇㄴㅁㄹㅇㅁㄴㄹ', TIMESTAMP '2026-07-15 11:24:00', CAST(NULL AS TIMESTAMP) FROM DUAL
    UNION ALL SELECT 'INFO', 'fdfd', 'admin', 'test162',
           'dddd', TIMESTAMP '2026-07-22 11:56:47', CAST(NULL AS TIMESTAMP) FROM DUAL
    UNION ALL SELECT 'NOTICE', 'ㄹㅇ', 'admin', 'test162',
           'ㄹㄴ어ㅏㄻ니ㅏ얼마ㅓㄹ민ㅇㄹㄴㄹ', TIMESTAMP '2026-07-24 16:25:34', TIMESTAMP '2026-07-24 16:37:19' FROM DUAL
    UNION ALL SELECT 'QNA', 'ㄹㅇㄴㄹㅇㅁㄴㄹ', 'test020', 'test162',
           'fdsfsdfdsf', TIMESTAMP '2026-07-24 16:40:22', CAST(NULL AS TIMESTAMP) FROM DUAL
    UNION ALL SELECT 'QNA', 'fdfdf', 'test021', 'test002',
           'fsdfasdf', TIMESTAMP '2026-07-24 17:02:41', CAST(NULL AS TIMESTAMP) FROM DUAL
    UNION ALL SELECT 'INFO', 'ㄹㅇㄴㅁㄹ', 'admin', 'test162',
           'fdsfasdf', TIMESTAMP '2026-07-24 17:25:29', CAST(NULL AS TIMESTAMP) FROM DUAL
)
SELECT
    SEQ_BOARD_COMMENT.NEXTVAL,
    b.BOARD_ID,
    commenter.MEMBER_ID,
    d.CONTENT,
    d.CREATED_AT,
    d.UPDATED_AT
FROM COMMENT_DATA d
JOIN BOARD b
    ON b.BOARD_TYPE = d.BOARD_TYPE
   AND b.TITLE = d.BOARD_TITLE
JOIN APP_MEMBER board_writer
    ON board_writer.MEMBER_ID = b.MEMBER_ID
   AND board_writer.LOGIN_ID = d.BOARD_WRITER_LOGIN
JOIN APP_MEMBER commenter
    ON commenter.LOGIN_ID = d.COMMENT_WRITER_LOGIN;

COMMIT;
SELECT COUNT(*) AS BOARD_COMMENT_COUNT FROM BOARD_COMMENT;
