/* ============================================================================
   PetCity 10 - 메인 배너·로그인 이력·방문 이력

   선행 파일: 01_member.sql 이후 실행 권장
   포함 내용: 테이블, PK/UNIQUE/CHECK, 외래키, 관련 인덱스, 관련 시퀀스
   제외 내용: 테스트·샘플 회원/병원/게시글/리뷰/신청 더미 데이터
============================================================================ */

-- AdminMainBannerMapper.xml에서 사용하는 MAIN_BANNER_SEQ만 생성합니다.

/* 1. 시퀀스 */

CREATE SEQUENCE MAIN_BANNER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SITE_LOGIN_HISTORY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SITE_VISIT_LOG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


/* 2. 테이블 */

CREATE TABLE MAIN_BANNER (
    BANNER_ID NUMBER,
    TITLE VARCHAR2(200 CHAR) NOT NULL,
    SUB_TITLE VARCHAR2(500 CHAR),
    IMAGE_URL VARCHAR2(1000 CHAR) NOT NULL,
    LINK_URL VARCHAR2(1000 CHAR),
    DISPLAY_ORDER NUMBER DEFAULT 1 NOT NULL,
    ACTIVE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    START_AT TIMESTAMP (6),
    END_AT TIMESTAMP (6),
    CREATED_AT TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_MAIN_BANNER PRIMARY KEY (BANNER_ID),
    CONSTRAINT CK_MAIN_BANNER_ACTIVE_YN CHECK (ACTIVE_YN IN ('Y', 'N')),
    CONSTRAINT CK_MAIN_BANNER_DISPLAY_ORDER CHECK (DISPLAY_ORDER >= 1),
    CONSTRAINT CK_MAIN_BANNER_PERIOD CHECK (
        START_AT IS NULL
        OR END_AT IS NULL
        OR START_AT <= END_AT
    )
);

CREATE TABLE SITE_LOGIN_HISTORY (
    LOGIN_HISTORY_ID NUMBER,
    MEMBER_ID NUMBER,
    LOGIN_ID VARCHAR2(100 CHAR),
    NICKNAME VARCHAR2(100 CHAR),
    ROLE VARCHAR2(30 CHAR),
    SESSION_ID VARCHAR2(200 CHAR),
    LOGIN_AT TIMESTAMP (6) NOT NULL,
    CREATED_AT TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_SITE_LOGIN_HISTORY PRIMARY KEY (LOGIN_HISTORY_ID)
);

CREATE TABLE SITE_VISIT_LOG (
    VISIT_ID NUMBER,
    VISIT_DATE DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    VISITOR_TYPE VARCHAR2(20) NOT NULL,
    VISITOR_KEY VARCHAR2(300) NOT NULL,
    MEMBER_ID NUMBER,
    SESSION_ID VARCHAR2(200) NOT NULL,
    IP_ADDRESS VARCHAR2(100),
    USER_AGENT VARCHAR2(1000),
    VISITED_URL VARCHAR2(1000),
    FIRST_VISITED_AT TIMESTAMP (6) NOT NULL,
    LAST_VISITED_AT TIMESTAMP (6) NOT NULL,
    CREATED_AT TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_SITE_VISIT_LOG_TYPE CHECK (
                VISITOR_TYPE IN (
                    'LOGIN',
                    'GUEST'
                )
            ),
    CONSTRAINT CK_SITE_VISIT_LOG_MEMBER CHECK (
                (
                    VISITOR_TYPE = 'LOGIN'
                    AND MEMBER_ID IS NOT NULL
                )
                OR
                (
                    VISITOR_TYPE = 'GUEST'
                    AND MEMBER_ID IS NULL
                )
            ),
    CONSTRAINT PK_SITE_VISIT_LOG PRIMARY KEY (VISIT_ID),
    CONSTRAINT UQ_SITE_VISIT_LOG_DAILY UNIQUE (VISIT_DATE, VISITOR_KEY)
);


/* 4. 조회·업무 인덱스 */

CREATE INDEX IDX_MAIN_BANNER_ACTIVE_ORDER
    ON MAIN_BANNER (ACTIVE_YN, DISPLAY_ORDER);

CREATE INDEX IDX_SITE_VISIT_LOG_DATE_TYPE
    ON SITE_VISIT_LOG (VISIT_DATE, VISITOR_TYPE);

CREATE INDEX IDX_SITE_VISIT_LOG_MEMBER
    ON SITE_VISIT_LOG (MEMBER_ID);


COMMIT;


/* 5. 메인 배너 시연 데이터 */

-- 새 BANNER_ID: 1 / 원본 BANNER_ID: 8
INSERT INTO MAIN_BANNER (BANNER_ID,TITLE,SUB_TITLE,IMAGE_URL,LINK_URL,DISPLAY_ORDER,ACTIVE_YN,START_AT,END_AT,CREATED_AT,UPDATED_AT)
SELECT
MAIN_BANNER_SEQ.NEXTVAL,'강아지가 처음이라면?','클릭해서 내 강아지에 대한 정보를 검색해보세요!','/uploads/main-banners/d2bf139d5117445baeb7fbeb23863889.png','https://mongmongiblug.blogspot.com/',1,'Y',NULL,NULL,TIMESTAMP '2026-07-29 05:36:53.314052',TIMESTAMP '2026-07-30 05:22:59.346362'
FROM DUAL;

-- 새 BANNER_ID: 2 / 원본 BANNER_ID: 9
INSERT INTO MAIN_BANNER (BANNER_ID,TITLE,SUB_TITLE,IMAGE_URL,LINK_URL,DISPLAY_ORDER,ACTIVE_YN,START_AT,END_AT,CREATED_AT,UPDATED_AT)
SELECT
MAIN_BANNER_SEQ.NEXTVAL,'고양이가 자꾸 할퀸다면?','이유를 알고 싶나요? 사진을 클릭해보세요!','/uploads/main-banners/864048ba03164a3b8014377acfcbe230.png','https://m.blog.naver.com/mnbogam/224250312430?recommendTrackingCode=2',2,'Y',NULL,NULL,TIMESTAMP '2026-07-30 04:41:00.204192',TIMESTAMP '2026-07-30 05:21:17.202318'
FROM DUAL;

-- 새 BANNER_ID: 3 / 원본 BANNER_ID: 10
INSERT INTO MAIN_BANNER (BANNER_ID,TITLE,SUB_TITLE,IMAGE_URL,LINK_URL,DISPLAY_ORDER,ACTIVE_YN,START_AT,END_AT,CREATED_AT,UPDATED_AT)
SELECT
MAIN_BANNER_SEQ.NEXTVAL,'우리 아이의 건강을 위협하는 기생충','기생충 제거하는 방법이 궁금하신가요? 사진을 클릭해보세요!','/uploads/main-banners/c0d2ad6c8eda4758b35234f170037564.png','https://www.youtube.com/watch?v=HWtRXxwSDsw',3,'Y',NULL,NULL,TIMESTAMP '2026-07-30 04:44:25.171098',TIMESTAMP '2026-07-30 05:23:10.43058'
FROM DUAL;

-- 새 BANNER_ID: 4 / 원본 BANNER_ID: 11
INSERT INTO MAIN_BANNER (BANNER_ID,TITLE,SUB_TITLE,IMAGE_URL,LINK_URL,DISPLAY_ORDER,ACTIVE_YN,START_AT,END_AT,CREATED_AT,UPDATED_AT)
SELECT
MAIN_BANNER_SEQ.NEXTVAL,'귀여운 슈가글라이더','이 귀여운 친구는 밥을 얼마나 먹을까요?','/uploads/main-banners/e57da7ca201047d5b74b441a90a435b1.png','https://blog.naver.com/simba726/224274382812',4,'Y',NULL,NULL,TIMESTAMP '2026-07-30 04:46:55.684034',TIMESTAMP '2026-07-30 04:46:55.684034'
FROM DUAL;

COMMIT;

SELECT COUNT(*) AS MAIN_BANNER_COUNT,
       MIN(BANNER_ID) AS MIN_BANNER_ID,
       MAX(BANNER_ID) AS MAX_BANNER_ID
FROM MAIN_BANNER;
