
/* ============================================================================
   PetCity 전체 생성 결과 검증

   01-00부터 10-00까지 순서대로 실행한 뒤 마지막에 실행합니다.
============================================================================ */

/* 1. 테이블 수: 예상 35 */
SELECT COUNT(*) AS TABLE_COUNT
FROM USER_TABLES
WHERE TABLE_NAME IN (
    'APP_MEMBER',
    'MEMBER_SECURITY_AUDIT',
    'ANIMAL_TYPE',
    'MEDICAL_SERVICE',
    'MEDICAL_SUBJECT',
    'MEMBER_PET',
    'HOSPITAL',
    'HOSPITAL_ANIMAL',
    'HOSPITAL_SERVICE',
    'HOSPITAL_MEDICAL_SUBJECT',
    'HOSPITAL_REVIEW',
    'HOSPITAL_LIKE',
    'FAVORITE_HOSPITAL',
    'HOSPITAL_OWNER_REQUEST',
    'OWNER_REQUEST_ANIMAL',
    'OWNER_REQUEST_SERVICE',
    'OWNER_REQUEST_MEDICAL_SUBJECT',
    'HOSPITAL_UPDATE_REQUEST',
    'HOSPITAL_UPDATE_REQUEST_ANIMAL',
    'HOSPITAL_UPDATE_REQUEST_SERVICE',
    'HOSPITAL_UPDATE_REQUEST_MEDICAL_SUBJECT',
    'HOSPITAL_DELETE_HISTORY',
    'BOARD',
    'BOARD_COMMENT',
    'BOARD_IMAGE',
    'BOARD_VIEW_HISTORY',
    'CHATBOT_CATEGORY',
    'CHATBOT_FAQ_SETTING',
    'CUSTOMER_CHAT_GUEST',
    'CHAT_GUEST_DAILY_USAGE',
    'CUSTOMER_CHAT_ROOM',
    'CUSTOMER_CHAT_MESSAGE',
    'MAIN_BANNER',
    'SITE_LOGIN_HISTORY',
    'SITE_VISIT_LOG'
);


/* 2. 직접 생성 시퀀스 수: 예상 19 */
SELECT COUNT(*) AS SEQUENCE_COUNT
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME IN (
    'SEQ_APP_MEMBER',
    'SEQ_MEMBER_SECURITY_AUDIT',
    'SEQ_ANIMAL_TYPE',
    'SEQ_MEDICAL_SERVICE',
    'SEQ_MEMBER_PET',
    'SEQ_HOSPITAL',
    'SEQ_HOSPITAL_REVIEW',
    'SEQ_HOSPITAL_OWNER_REQUEST',
    'SEQ_HOSPITAL_DELETE_HISTORY',
    'SEQ_BOARD',
    'SEQ_BOARD_COMMENT',
    'SEQ_BOARD_IMAGE',
    'SEQ_CHATBOT_CATEGORY',
    'SEQ_CUSTOMER_CHAT_GUEST',
    'SEQ_CUSTOMER_CHAT_ROOM',
    'SEQ_CUSTOMER_CHAT_MESSAGE',
    'MAIN_BANNER_SEQ',
    'SEQ_SITE_LOGIN_HISTORY',
    'SEQ_SITE_VISIT_LOG'
);


/* 3. 주요 데이터 건수 */
SELECT 'APP_MEMBER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT, 201 AS EXPECTED_COUNT FROM APP_MEMBER
UNION ALL SELECT 'ANIMAL_TYPE', COUNT(*), 37 FROM ANIMAL_TYPE
UNION ALL SELECT 'MEDICAL_SERVICE', COUNT(*), 9 FROM MEDICAL_SERVICE
UNION ALL SELECT 'MEDICAL_SUBJECT', COUNT(*), 19 FROM MEDICAL_SUBJECT
UNION ALL SELECT 'HOSPITAL', COUNT(*), 193 FROM HOSPITAL
UNION ALL SELECT 'HOSPITAL_ANIMAL', COUNT(*), 929 FROM HOSPITAL_ANIMAL
UNION ALL SELECT 'HOSPITAL_SERVICE', COUNT(*), 197 FROM HOSPITAL_SERVICE
UNION ALL SELECT 'HOSPITAL_MEDICAL_SUBJECT', COUNT(*), 489 FROM HOSPITAL_MEDICAL_SUBJECT
UNION ALL SELECT 'BOARD', COUNT(*), 121 FROM BOARD
UNION ALL SELECT 'BOARD_COMMENT', COUNT(*), 8 FROM BOARD_COMMENT
UNION ALL SELECT 'BOARD_IMAGE', COUNT(*), 21 FROM BOARD_IMAGE
UNION ALL SELECT 'BOARD_VIEW_HISTORY', COUNT(*), 47 FROM BOARD_VIEW_HISTORY
UNION ALL SELECT 'CHATBOT_CATEGORY', COUNT(*), 6 FROM CHATBOT_CATEGORY
UNION ALL SELECT 'CHATBOT_FAQ_SETTING', COUNT(*), 15 FROM CHATBOT_FAQ_SETTING
UNION ALL SELECT 'MAIN_BANNER', COUNT(*), 4 FROM MAIN_BANNER;


/* 4. 병원 보유 수와 USER/OWNER 권한 불일치: 예상 0건 */
SELECT M.MEMBER_ID,
       M.LOGIN_ID,
       M.ROLE,
       (
           SELECT COUNT(*)
           FROM HOSPITAL H
           WHERE H.OWNER_ID = M.MEMBER_ID
       ) AS HOSPITAL_COUNT
FROM APP_MEMBER M
WHERE M.ROLE IN ('USER', 'OWNER')
  AND (
       (
           EXISTS (
               SELECT 1
               FROM HOSPITAL H
               WHERE H.OWNER_ID = M.MEMBER_ID
           )
           AND M.ROLE <> 'OWNER'
       )
       OR
       (
           NOT EXISTS (
               SELECT 1
               FROM HOSPITAL H
               WHERE H.OWNER_ID = M.MEMBER_ID
           )
           AND M.ROLE <> 'USER'
       )
  );


/* 5. 병원 관계 데이터의 고아 레코드: 각각 예상 0 */
SELECT 'HOSPITAL_ANIMAL_HOSPITAL' AS CHECK_NAME, COUNT(*) AS ERROR_COUNT
FROM HOSPITAL_ANIMAL HA
LEFT JOIN HOSPITAL H ON H.HOSPITAL_ID = HA.HOSPITAL_ID
WHERE H.HOSPITAL_ID IS NULL
UNION ALL
SELECT 'HOSPITAL_ANIMAL_ANIMAL', COUNT(*)
FROM HOSPITAL_ANIMAL HA
LEFT JOIN ANIMAL_TYPE A ON A.ANIMAL_ID = HA.ANIMAL_ID
WHERE A.ANIMAL_ID IS NULL
UNION ALL
SELECT 'HOSPITAL_SERVICE_HOSPITAL', COUNT(*)
FROM HOSPITAL_SERVICE HS
LEFT JOIN HOSPITAL H ON H.HOSPITAL_ID = HS.HOSPITAL_ID
WHERE H.HOSPITAL_ID IS NULL
UNION ALL
SELECT 'HOSPITAL_SERVICE_SERVICE', COUNT(*)
FROM HOSPITAL_SERVICE HS
LEFT JOIN MEDICAL_SERVICE MS ON MS.SERVICE_ID = HS.SERVICE_ID
WHERE MS.SERVICE_ID IS NULL
UNION ALL
SELECT 'HOSPITAL_SUBJECT_HOSPITAL', COUNT(*)
FROM HOSPITAL_MEDICAL_SUBJECT HMS
LEFT JOIN HOSPITAL H ON H.HOSPITAL_ID = HMS.HOSPITAL_ID
WHERE H.HOSPITAL_ID IS NULL
UNION ALL
SELECT 'HOSPITAL_SUBJECT_SUBJECT', COUNT(*)
FROM HOSPITAL_MEDICAL_SUBJECT HMS
LEFT JOIN MEDICAL_SUBJECT MS ON MS.SUBJECT_ID = HMS.SUBJECT_ID
WHERE MS.SUBJECT_ID IS NULL;


/* 6. 병원장 신청 제약조건과 병원 FK 삭제 규칙 */
SELECT UC.CONSTRAINT_NAME,
       UC.CONSTRAINT_TYPE,
       UCC.COLUMN_NAME,
       UC.DELETE_RULE,
       UC.STATUS,
       UC.SEARCH_CONDITION_VC
FROM USER_CONSTRAINTS UC
LEFT JOIN USER_CONS_COLUMNS UCC
       ON UCC.OWNER = UC.OWNER
      AND UCC.CONSTRAINT_NAME = UC.CONSTRAINT_NAME
      AND UCC.TABLE_NAME = UC.TABLE_NAME
WHERE UC.TABLE_NAME = 'HOSPITAL_OWNER_REQUEST'
  AND UC.CONSTRAINT_NAME IN (
      'CK_OWNER_REQUEST_HOSPITAL',
      'FK_OWNER_REQ_HOSPITAL'
  )
ORDER BY UC.CONSTRAINT_NAME;


/* 7. 비활성화된 제약조건: 예상 0건 */
SELECT TABLE_NAME,
       CONSTRAINT_NAME,
       CONSTRAINT_TYPE,
       STATUS
FROM USER_CONSTRAINTS
WHERE STATUS <> 'ENABLED'
ORDER BY TABLE_NAME, CONSTRAINT_TYPE, CONSTRAINT_NAME;


/* 8. INVALID 객체: 예상 0건 */
SELECT OBJECT_NAME,
       OBJECT_TYPE,
       STATUS
FROM USER_OBJECTS
WHERE STATUS <> 'VALID'
ORDER BY OBJECT_TYPE, OBJECT_NAME;


/* 9. 주요 시퀀스의 다음 번호 확인 */
SELECT SEQUENCE_NAME,
       LAST_NUMBER,
       INCREMENT_BY
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME IN (
    'SEQ_APP_MEMBER',
    'SEQ_HOSPITAL',
    'SEQ_BOARD',
    'SEQ_BOARD_COMMENT',
    'SEQ_BOARD_IMAGE',
    'SEQ_CHATBOT_CATEGORY',
    'MAIN_BANNER_SEQ'
)
ORDER BY SEQUENCE_NAME;
