DROP TABLE HOSPITAL_UPDATE_REQUEST CASCADE CONSTRAINTS;


/* =====================================================
   3. 통합 병원 관리 요청 테이블 생성
   UPDATE     : 병원정보 수정 요청
   TEMP_CLOSE : 휴업 요청
   CLOSE      : 폐업 요청
===================================================== */

CREATE TABLE HOSPITAL_UPDATE_REQUEST (

                                         REQUEST_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    /* 요청 대상 병원 / 요청한 병원장 */
                                         HOSPITAL_ID NUMBER NOT NULL,
                                         MEMBER_ID NUMBER NOT NULL,

    /* UPDATE, TEMP_CLOSE, CLOSE */
                                         REQUEST_TYPE VARCHAR2(20) DEFAULT 'UPDATE' NOT NULL,

    /* =================================================
       병원정보 수정 요청에서 사용하는 정보
       휴업 / 폐업 요청에서는 대부분 NULL
    ================================================= */

                                         APPLICANT_NAME VARCHAR2(50),
                                         BUSINESS_NUMBER VARCHAR2(30),
                                         DOCUMENT_URL VARCHAR2(1000),

                                         HOSPITAL_NAME VARCHAR2(200),
                                         HOSPITAL_PHONE VARCHAR2(50),

                                         HOSPITAL_ADDRESS VARCHAR2(500),
                                         HOSPITAL_DETAIL_ADDRESS VARCHAR2(500),
                                         HOSPITAL_DISTRICT VARCHAR2(50),
                                         HOSPITAL_WEBSITE_URL VARCHAR2(1000),

                                         HOSPITAL_LATITUDE NUMBER(18, 9),
                                         HOSPITAL_LONGITUDE NUMBER(18, 9),

    /* 기존 HospitalUpdateMapper 호환용 운영 정보 */
                                         MEDICAL_SUBJECTS VARCHAR2(2000),
                                         OPEN_TIME VARCHAR2(100),
                                         CLOSE_TIME VARCHAR2(100),
                                         LUNCH_TIME VARCHAR2(100),
                                         HOLIDAY VARCHAR2(500),

                                         HOSPITAL_DOCTOR_INFO VARCHAR2(1000),
                                         HOSPITAL_DESCRIPTION VARCHAR2(2000),
                                         HOSPITAL_IMAGE_URL VARCHAR2(1000),
                                         HOSPITAL_NOTE VARCHAR2(2000),

    /* =================================================
       휴업 / 폐업 요청 정보
    ================================================= */

                                         TEMP_CLOSE_START_AT TIMESTAMP,
                                         TEMP_CLOSE_END_AT TIMESTAMP,

    /* 휴업 사유 또는 폐업 사유 */
                                         REQUEST_REASON VARCHAR2(500),

    /* =================================================
       관리자 처리 정보
    ================================================= */

                                         STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,

                                         CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                                         PROCESSED_AT TIMESTAMP,
                                         PROCESSED_BY NUMBER,
                                         REJECT_REASON VARCHAR2(1000),

                                         CONSTRAINT CK_HUR_REQUEST_TYPE
                                             CHECK (REQUEST_TYPE IN ('UPDATE', 'TEMP_CLOSE', 'CLOSE')),

                                         CONSTRAINT CK_HUR_STATUS
                                             CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED')),

    /* 휴업 요청은 시작일·종료일이 반드시 필요 */
                                         CONSTRAINT CK_HUR_TEMP_CLOSE_PERIOD
                                             CHECK (
                                                 REQUEST_TYPE != 'TEMP_CLOSE'
                                                 OR (
                                                 TEMP_CLOSE_START_AT IS NOT NULL
                                                 AND TEMP_CLOSE_END_AT IS NOT NULL
                                                 AND TEMP_CLOSE_END_AT > TEMP_CLOSE_START_AT
                                                 )
),

    CONSTRAINT FK_HUR_HOSPITAL
        FOREIGN KEY (HOSPITAL_ID)
        REFERENCES HOSPITAL(HOSPITAL_ID),

    CONSTRAINT FK_HUR_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES APP_MEMBER(MEMBER_ID),

    CONSTRAINT FK_HUR_PROCESSED_BY
        FOREIGN KEY (PROCESSED_BY)
        REFERENCES APP_MEMBER(MEMBER_ID)
);


/* =====================================================
   4. 수정 요청의 다중 선택값 저장 테이블
===================================================== */

CREATE TABLE HOSPITAL_UPDATE_REQUEST_ANIMAL (
                                                REQUEST_ID NUMBER NOT NULL,
                                                ANIMAL_ID NUMBER NOT NULL,

                                                CONSTRAINT PK_HUR_ANIMAL
                                                    PRIMARY KEY (REQUEST_ID, ANIMAL_ID),

                                                CONSTRAINT FK_HUR_ANIMAL_REQUEST
                                                    FOREIGN KEY (REQUEST_ID)
                                                        REFERENCES HOSPITAL_UPDATE_REQUEST(REQUEST_ID)
                                                        ON DELETE CASCADE,

                                                CONSTRAINT FK_HUR_ANIMAL_TYPE
                                                    FOREIGN KEY (ANIMAL_ID)
                                                        REFERENCES ANIMAL_TYPE(ANIMAL_ID)
);

CREATE TABLE HOSPITAL_UPDATE_REQUEST_SERVICE (
                                                 REQUEST_ID NUMBER NOT NULL,
                                                 SERVICE_ID NUMBER NOT NULL,

                                                 CONSTRAINT PK_HUR_SERVICE
                                                     PRIMARY KEY (REQUEST_ID, SERVICE_ID),

                                                 CONSTRAINT FK_HUR_SERVICE_REQUEST
                                                     FOREIGN KEY (REQUEST_ID)
                                                         REFERENCES HOSPITAL_UPDATE_REQUEST(REQUEST_ID)
                                                         ON DELETE CASCADE,

                                                 CONSTRAINT FK_HUR_SERVICE_TYPE
                                                     FOREIGN KEY (SERVICE_ID)
                                                         REFERENCES MEDICAL_SERVICE(SERVICE_ID)
);

CREATE TABLE HOSPITAL_UPDATE_REQUEST_MEDICAL_SUBJECT (
                                                         REQUEST_ID NUMBER NOT NULL,
                                                         SUBJECT_ID NUMBER NOT NULL,

                                                         CONSTRAINT PK_HUR_SUBJECT
                                                             PRIMARY KEY (REQUEST_ID, SUBJECT_ID),

                                                         CONSTRAINT FK_HUR_SUBJECT_REQUEST
                                                             FOREIGN KEY (REQUEST_ID)
                                                                 REFERENCES HOSPITAL_UPDATE_REQUEST(REQUEST_ID)
                                                                 ON DELETE CASCADE,

                                                         CONSTRAINT FK_HUR_SUBJECT_TYPE
                                                             FOREIGN KEY (SUBJECT_ID)
                                                                 REFERENCES MEDICAL_SUBJECT(SUBJECT_ID)
);


/* =====================================================
   5. 조회 성능용 인덱스
===================================================== */

CREATE INDEX IDX_HUR_HOSPITAL_STATUS
    ON HOSPITAL_UPDATE_REQUEST (
                                HOSPITAL_ID,
                                STATUS,
                                CREATED_AT
        );

CREATE INDEX IDX_HUR_MEMBER_STATUS
    ON HOSPITAL_UPDATE_REQUEST (
                                MEMBER_ID,
                                STATUS,
                                CREATED_AT
        );

CREATE INDEX IDX_HUR_TYPE_STATUS
    ON HOSPITAL_UPDATE_REQUEST (
                                REQUEST_TYPE,
                                STATUS,
                                CREATED_AT
        );

COMMIT;

ALTER TABLE HOSPITAL_UPDATE_REQUEST
    RENAME COLUMN LUNCH_TIME TO BREAK_TIME;

ALTER TABLE HOSPITAL_UPDATE_REQUEST
    RENAME COLUMN HOLIDAY TO CLOSED_DAYS;

COMMIT;
--ㅇㅇ--