-- [상각_07-19_20 / 필수 적용 / 실행 순서 1]
-- 구분: 기존 APP_MEMBER 테이블 수정 SQL
-- 기능: 일반·SNS 회원 탈퇴 취소 및 계정 복구용 복구코드 해시 저장
-- 보안: 복구코드 원문은 저장하지 않고 PasswordEncoder 해시만 저장합니다.
-- 8081 원본 SQL(0~19번)은 수정하지 않습니다.

DECLARE
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'APP_MEMBER'
       AND COLUMN_NAME = 'RECOVERY_TOKEN_HASH';

    IF V_COUNT = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE APP_MEMBER ADD RECOVERY_TOKEN_HASH VARCHAR2(200 CHAR)';
    END IF;
END;
/

-- 구버전 DB에 DELETE_REASON이 없는 경우에만 자동 추가합니다.
DECLARE
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'APP_MEMBER'
       AND COLUMN_NAME = 'DELETE_REASON';

    IF V_COUNT = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE APP_MEMBER ADD DELETE_REASON VARCHAR2(500 CHAR)';
    END IF;
END;
/

