-- [상각_07-19 / 필수 적용 / 실행 순서 3]
-- 구분: 보안 감사 이력 신규 테이블·시퀀스·인덱스 추가 SQL
-- 기능: 회원 탈퇴·복구 성공 및 실패 이력을 1년간 보관
-- 회원 탈퇴·복구 보안 감사 이력은 1년 보관 후 애플리케이션 스케줄러가 자동 삭제
-- 복구코드와 이메일 인증번호 원문은 저장하지 않습니다.
CREATE TABLE MEMBER_SECURITY_AUDIT (
    AUDIT_ID       NUMBER PRIMARY KEY,
    MEMBER_ID      NUMBER,
    LOGIN_ID       VARCHAR2(100 CHAR) NOT NULL,
    NICKNAME       VARCHAR2(100 CHAR),
    LOGIN_TYPE     VARCHAR2(30 CHAR),
    EVENT_TYPE     VARCHAR2(50 CHAR) NOT NULL,
    EVENT_RESULT   VARCHAR2(20 CHAR) NOT NULL,
    EVENT_REASON   VARCHAR2(1000 CHAR),
    IP_ADDRESS     VARCHAR2(64 CHAR),
    OCCURRED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    EXPIRES_AT     TIMESTAMP NOT NULL,
    CONSTRAINT CK_MEMBER_SECURITY_AUDIT_RESULT
        CHECK (EVENT_RESULT IN ('SUCCESS', 'FAILURE'))
);

-- 회원 영구 삭제 후에도 1년간 감사 이력을 유지해야 하므로 MEMBER_ID 외래키는 설정하지 않습니다.
CREATE SEQUENCE SEQ_MEMBER_SECURITY_AUDIT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IX_MEMBER_SECURITY_AUDIT_MEMBER ON MEMBER_SECURITY_AUDIT (MEMBER_ID, OCCURRED_AT DESC);
CREATE INDEX IX_MEMBER_SECURITY_AUDIT_EXPIRES ON MEMBER_SECURITY_AUDIT (EXPIRES_AT);

SELECT AUDIT_ID, MEMBER_ID, LOGIN_ID, EVENT_TYPE, EVENT_RESULT, OCCURRED_AT, EXPIRES_AT
  FROM MEMBER_SECURITY_AUDIT
 ORDER BY OCCURRED_AT DESC;
