/* 1. 기존 테이블 삭제 (초기화 작업) */
DROP TABLE ANIMAL_TYPE CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_ANIMAL_TYPE;

/* 2. 테이블 생성 (계층형 구조 적용) */
CREATE TABLE ANIMAL_TYPE (
                             ANIMAL_ID    NUMBER PRIMARY KEY,
                             ANIMAL_NAME  VARCHAR2(50 CHAR) NOT NULL,
                             CATEGORY     VARCHAR2(50 CHAR) NOT NULL,
                             PARENT_ID    NUMBER,
                             CONSTRAINT FK_ANIMAL_PARENT FOREIGN KEY (PARENT_ID) REFERENCES ANIMAL_TYPE(ANIMAL_ID)
);

/* 3. 시퀀스 생성 */
CREATE SEQUENCE SEQ_ANIMAL_TYPE START WITH 1 INCREMENT BY 1 NOCACHE;

/* 4. 대분류 데이터 삽입 */
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (1, '강아지', '일반', NULL);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (2, '고양이', '일반', NULL);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (3, '파충류', '특수', NULL);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (4, '설치류', '특수', NULL);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (5, '어류', '특수', NULL);

/* 5. 중분류 데이터 삽입 (강아지 하위) */
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (6, '말티즈', '일반', 1);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (7, '시츄', '일반', 1);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (8, '골든리트리버', '일반', 1);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (9, '보더콜리', '일반', 1);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (10, '비숑프리제', '일반', 1);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (11, '기타(소형견)', '일반', 1);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (12, '기타(중형견)', '일반', 1);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (13, '기타(대형견)', '일반', 1);
/* 6. 중분류 데이터 삽입 (고양이 하위)*/
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (14, '코리안숏헤어', '일반', 2);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (15, '아메리칸숏헤어', '일반', 2);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (16, '먼치킨', '일반', 2);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (17, '페르시안', '일반', 2);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (18, '러시안블루', '일반', 2);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (19, '샤미즈', '일반', 2);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (20, '스코티시폴드', '일반', 2);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (21, '기타묘', '일반', 2);
/* 7. 중분류 데이터 삽입 (파충류/설치류 예시) */
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (22, '도마뱀', '특수', 3);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (23, '거북이', '특수', 3);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (24, '뱀', '특수', 3);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (25, '카멜레온', '특수', 3);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (26, '기타', '특수', 3);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (27, '다람쥐', '특수', 4);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (28, '날다람쥐', '특수', 4);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (29, '햄스터', '특수', 4);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (30, '토끼', '특수', 4);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (31, '친칠라', '특수', 4);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (32, '기타', '특수', 4);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (33, '금붕어', '특수', 5);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (34, '잉어', '특수', 5);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (35, '열대어', '특수', 5);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (36, '고대어', '특수', 5);
INSERT INTO ANIMAL_TYPE (ANIMAL_ID, ANIMAL_NAME, CATEGORY, PARENT_ID) VALUES (37, '기타', '특수', 5);



/* 커밋 */
COMMIT;