-- 1. 새로운 진료 과목 테이블 생성 (MEDICAL_SUBJECT)
CREATE TABLE MEDICAL_SUBJECT (
    SUBJECT_ID NUMBER PRIMARY KEY,
    SUBJECT_NAME VARCHAR2(100) NOT NULL
);

-- 2. 정제된 진료 과목 데이터 삽입
INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (1, '내과');
INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (2, '외과');
INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (3, '정형외과');
INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (4, '피부과');
INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (5, '안과');
INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (6, '치과');
INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (7, '영상의학과');
INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (8, '이비인후과');
INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (9, '비뇨기과');
INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (10, '신경외과');
INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (11, '산과');
INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (12, '심장내과');
INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (13, '마취통증의학과');
INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (14, '예방의학과');
INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (15, '재활의학과');
INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (16, '중성화');
INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (17, '영양상담');
INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (18, '헌혈');
INSERT INTO MEDICAL_SUBJECT (SUBJECT_ID, SUBJECT_NAME) VALUES (19, '미용');

-- 3. 저장
COMMIT;