/* 리뷰 테이블에 펫 ID 및 답글 관련 컬럼 추가 */
ALTER TABLE HOSPITAL_REVIEW ADD PET_ID NUMBER;
ALTER TABLE HOSPITAL_REVIEW ADD REPLY_CONTENT VARCHAR2(2000);
ALTER TABLE HOSPITAL_REVIEW ADD REPLY_CREATED_AT TIMESTAMP;
ALTER TABLE HOSPITAL_REVIEW ADD REPLY_ROLE VARCHAR2(20);

COMMIT;