ALTER TABLE HOSPITAL_OWNER_REQUEST
    MODIFY (
    HOSPITAL_ID NULL
    );

ALTER TABLE HOSPITAL_OWNER_REQUEST
    ADD CONSTRAINT CK_OWNER_REQUEST_HOSPITAL
        CHECK (
            STATUS <> 'APPROVED'
                OR HOSPITAL_ID IS NOT NULL
            );