CREATE TABLE HOSPITAL_UPDATE_REQUEST (
                                         REQUEST_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         HOSPITAL_ID NUMBER NOT NULL,
                                         MEMBER_ID NUMBER NOT NULL,
                                         MEDICAL_SUBJECTS VARCHAR2(500),
                                         OPEN_TIME VARCHAR2(20),
                                         CLOSE_TIME VARCHAR2(20),
                                         LUNCH_TIME VARCHAR2(50),
                                         HOLIDAY VARCHAR2(100),
                                         STATUS VARCHAR2(20) DEFAULT 'PENDING',
                                         CREATED_AT DATE DEFAULT SYSDATE,
                                         PROCESSED_AT DATE,
                                         REJECT_REASON VARCHAR2(1000)
);